### ISSUE TITLE
Cannot convert undefined to BigInt [bug] 

### ISSUE THREAD

**Issue by YVeselovskyi** [WalletConnect/web3modal#1083]
### Link to minimal reproducible example

https://codesandbox.io/p/sandbox/github/WalletConnect/web3modal-examples/tree/main/html-wagmi

### Summary

This issue is reproducible in your example.

There are actually two issues:

1. Cannot convert undefined to BigInt
2. ContractFunctionExecutionError: Cannot decode zero data ("0x") with ABI parameters.

To reproduce this error just try to connect and disconnect wallet multiple times.

### List of related npm package versions

"@wagmi/core": "^1.2.0",
"@web3modal/ethereum": "^2.4.7",
"@web3modal/html": "^2.4.7",
"viem": "^1.0.7"

**Comment by 0xAsimetriq** [comment]
Example you linked doesn't seem to be working (no connect button rendered). I just tried this locally with same `html-wagmi` example and was not able to reproduce the issue.


https://github.com/WalletConnect/web3modal/assets/3154053/e0cd34ed-9237-4ae6-9a72-aba02f7113d5

Do you have more specifics / can you get that sandbox to work in order to replicate it? Also sounds like something from downstream dependencies, maybe wagmi or viem.

**Comment by jxom** [comment]
The issue occurs usually when the target is below ES2020 (which doesn't support BigInt).

**Comment by joshuanwankwo** [comment]
Try making sure your wallet is on the network(mainnet/testnest) as the deployed smart contract.
