### ISSUE TITLE
The websocket will automatically disconnect after a certain period of time after successful connection

### ISSUE THREAD

**Issue by pangpang007** [WalletConnect/web3modal#1205]
I used web3modal in a React project and used the useWeb3Modal hooks to trigger a pop-up for wallet connection. 
After successfully connecting for a while, the websocket stops receiving messages without any indication of disconnection. 
And I used the useAccount hook provided by wagmi to monitor whether the wallet is still connected, and then the onDisconnect function I provided was also executed. When trying to reconnect, an error occurs with the message 'Connection Declined.' 
The only way to reconnect is by refreshing the page in the browser.

@web3modal/ethereum  v2.6.1 
@web3modal/react v2.6.1

this is my wagmi config

<img width="697" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/29764139/21e1748d-0c96-4502-90e4-5cd00dd49d75">

and this is error pop-up

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/29764139/e43bfcdf-0261-4839-81a9-9250b7f589ad)

It seems that the issue lies in the reconnection process, as the previous connection has not been disconnected yet. Can you help me out so that I can maintain the connection continuously after connecting to the wallet?

**Comment by 0xAsimetriq** [comment]
`ConnectoAlreadyConnectedError` means that wagmi's connector is already in connected state and you are trying to connect again. This will not work and requires to be disconnected first. In terms of WalletConnect websocket it will reconnect automatically when it is needed again (although it should remain open most of the time).

This error usually happens when you don't handle connection state properly i.e. continue showing connect button when it should not be visible.

Will also close for now as there is no minimal reproducible example for me to test (unable to get this replicated after keeping https://web3modal.com open for a while).

Feel free to re-open if any extra details pop up / you can provide an example and follow issue template here in web3modal repo, will have another look.
