### ISSUE TITLE
[bug] Error redirect when i try call smart contract

### ISSUE THREAD

**Issue by hoangphuc36006** [WalletConnect/web3modal#1220]
### Link to minimal reproducible example

.....

### Summary

hi sir , I got this error on trust wallet and meta mask
when user clicks a button on website, it redirects to trust wallet / meta mask
it wants to call 2 or more smart contracts at once
but when the user accepts (or declines) the first smart contract call, it is redirected to the website immediately.
that doesn't happen above safepal wallet...
so , is there an or options attribute to adjust this redirect ?

### List of related npm package versions

@web3modal/ethereum@2.7.0
@web3modal/html@2.6.2
@WagmiCore

**Comment by 0xAsimetriq** [comment]
I don't think this will work as of now I'm afraid. Under the hood web3modal uses walletconnect dependencies that redirect to mobile app after a request (tx request for example) is made. To make multiple in a row, you would ideally await them one by one and call them in order.

This will redirect user to the wallet and back (although ux is not great due to many jumps between the apps). If wallet is not redirecting back correctly (in fact anything that happens within wallet), this is out of our control, I'd suggest reaching out to them and asking to why that is.

We are planning / working on "batch requests" that will allow to send multiple in order, should be arriving soonish.
