### ISSUE TITLE
[bug] wrong wallet deep link prompted

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1227]
### Link to minimal reproducible example

lab.web3modal.com

### Summary

wrong wallet deep link prompted.
Steps to repro:
1. Open [lab.web3modal.com](http://lab.web3modal.com/) on iOS Safari
1. Pair Blocto (or any other wallet)
1. Go back to dapp and disconnect
1. Click connect and Copy URL
1. Pair via iOS Sample Wallet
1. Go back to dapp and Click sign

Expected behavior: not sure
Actual behavior: Dapp prompts “Open Blocto” which is not the paired wallet (edited)

### List of related npm package versions

Latest

**Comment by icedevml** [comment]
The issue is that Web3Modal will remember the last manually chosen wallet in the `CoreUtil.WALLETCONNECT_DEEPLINK_CHOICE` key of localStorage. This key is only written when the user manually picks a wallet app by clicking on the icon.

Certain logic in the modal depends on the value of that key. It appears that the key is not overridden/removed when you relaunch the modal and use the QR code/copy URI feature. Thus, it will still remember the old wallet and cause buggy behavior.
