### ISSUE TITLE
Metamask not shown in the selection window when both Metamask and Nifty are installed

### ISSUE THREAD

**Issue by michwill** [WalletConnect/web3modal#123]
Was noticed in Chrome browser having both extensions installed

**Comment by pedrouid** [comment]
Currently there isn't any standard way to support multiple inject providers in Window therefore it will be a race between which assigned the `ethereum` namespace last

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
