### ISSUE TITLE
[feature] It takes a long time to load `All Wallets` for the first time. I hope it can be optimized and improved.

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1339]
### What problem does this new feature solve?

It takes a long time to load `All Wallets` for the first time. I hope it can be optimized and improved.

### Describe the solution you'd like

When `modal is` opened when all wallets is not loaded, wallets will not be updated even after all wallets is loaded.
You need to close modal and then open modal to display all wallets.

When the list is not completely loaded
---
**Three situations occur randomly**, very unstable
Use the browser in incognito mode without caching for easy testing

Situation 1:
![002](https://github.com/WalletConnect/web3modal/assets/19625243/6c0457d7-9887-4b09-94a7-c5ee2219bcc0)

Situation 2:
![003](https://github.com/WalletConnect/web3modal/assets/19625243/c061f9bc-c4fb-463a-9e53-00ee00cbb139)

Situation 3:
![004](https://github.com/WalletConnect/web3modal/assets/19625243/2f00d308-046c-4a5b-977c-c9c2256c91f1)

When the list is loaded
---
The picture below shows the normal display

![001](https://github.com/WalletConnect/web3modal/assets/19625243/6dea1488-e815-479c-b867-1ffcbbb43f86)

**Comment by 0xAsimetriq** [comment]
We start pre-fetching initial data when modal is created, so it is usually in place when user clicks "connect" button. Requests are also cached across cdn, however given that you have custom configuration.

We've been experiencing degraded performance on api today (currently investigating), I think that's why your experience is slow right now. Closing this issue as all optimisations are already in place, you should see better performance as soon as we resolve ongoing issue.
