### ISSUE TITLE
[bug] on the wallet page, click the "copy link" button prompting  "Failed to copy"

### ISSUE THREAD

**Issue by yunnuowangluo** [WalletConnect/web3modal#1376]
### Link to minimal reproducible example

https://github.com/WalletConnect/web3modal/assets/5944479/3546c554-66cb-47a1-bead-fc45d6cb0463

### Summary

Vuejs introduces the Web3Modal module, compiles and deploys the site using "npm run build", connects to the "copy link" button on the wallet page, and clicks, prompting "Failed to copy". But it works normally when running in "npm run dev" mode.

![image](https://github.com/WalletConnect/web3modal/assets/5944479/3546c554-66cb-47a1-bead-fc45d6cb0463)

### List of related npm package versions

"@web3modal/core":  "version": "3.0.2",
"@web3modal/wagmi":   "version": "3.0.2",
"copy-to-clipboard": "^3.3.3"

**Comment by 0xAsimetriq** [comment]
I think this issue is due to `copy-to-clipboard` dependency you have? We use `navigator.clipboard.writeText` to perform this and that error occurs when this utility throws https://github.com/WalletConnect/web3modal/blob/V3/packages/core/src/utils/CoreHelperUtil.ts#L40

My hunch is that `copy-to-clipboard` library used might be altering this native browser api somehow, hence throwing. Or browser / device you are on doesn't support it.

Could you drop me your browser details and check if everything works when you remove that extra dependency? (you can use native browser apis as well, thus reducing your bundle size.)
