### ISSUE TITLE
[feature] Add excudedWalletIds

### ISSUE THREAD

**Issue by meri-maki** [WalletConnect/web3modal#1409]
### What problem does this new feature solve?

I remember having a ```excudedWalletIds``` (or something like that) option for walletConnectModal

I'm currently building a project on wagmi and Web3Modal (v3) and it would be really great to have an option to exclude certain Wallets from the modal. Mostly because not all wallets work correctly with some of the wagmi logic, and I would like the users of my app to avoid errors and lags (even if it costs them less wallets to choose from)

### Describe the solution you'd like

Add option ```excudedWalletIds``` for ```createWeb3Modal({})```

**Comment by glitch-txs** [comment]
Hi,
1. do you mean because some wallets are not EVM compliant or they have bugs?
2. Would this option only for desktop help? This wouldn't affect the functionality of the excluded wallets since they would only be shown on mobile but on desktop they can use the WalletConnect QR Code. Otherwise users that own these wallets won't be able to connect to your website.

We don't have this option currently documented, but you can use `includeWalletIds` and `excludeWalletIds` in v3.

**Comment by meri-maki** [comment]
@glitch-txs added ```excludeWalletIds``` to ```reateWeb3Modal({})``` and it worked!
Would be great if it's included in the docs, thanks!
