### ISSUE TITLE
Allow to use them providers on mobile as on desktop

### ISSUE THREAD

**Issue by rmeissner** [WalletConnect/web3modal#145]
I would like to be able to decide myself if all options should be able on mobile. Current on mobile the web3modal only allows to either use the injected provider or to use the selected providers (see https://github.com/Web3Modal/web3modal/blob/master/src/core/controllers/providers.ts#L77) it would be really helpful if this would not be enforced like that.

**Comment by miohtama** [comment]
@rmeissner I think decoupling the filtering code of not being internal might be a good solution.

* You can pass out your own provider list constructor, all package members are exported so that it is easy to create one 

* The default code (current) is used if no option is passed

Would this work?

**Comment by rmeissner** [comment]
Yes this is something I had in mind. In the project I tested that we pass in the provider options for wallet connect to only walletconnect and the injected is shown (which is expected), but on mobile suddenly only the injected shows up (but I want to use walletconnect with deeplinks :P ). 

To be fair the project used a very old template where it was still "web3connect", definitely need to update :D

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
