### ISSUE TITLE
[bug] - Number of wallets is shown as 0+ when using includeWalletsId option

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1474]
### Link to minimal reproducible example

https://github.com/glitch-txs/web3modal-v3

### Summary

"All Wallets" button number is 0+ when using includeWalletsId option

```ts
createWeb3Modal({ 
  wagmiConfig, 
  projectId, 
  chains,
  includeWalletIds:[
    "c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96",
    "4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0"
  ]
})
```

![image](https://github.com/WalletConnect/web3modal/assets/66949816/76e86fee-d3ca-43ec-8dfb-3f3ac76ab5e3)
![image](https://github.com/WalletConnect/web3modal/assets/66949816/a5ad31eb-0c36-43e0-9b46-a8d84a146b0d)

### List of related npm package versions

```
"@web3modal/wagmi": "^3.2.1",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"viem": "^1.19.0",
"wagmi": "^1.4.6"
```

**Comment by saintmaxi** [comment]
@glitch-txs 
Looks like this is just due to the rounding being done [here](https://github.com/WalletConnect/web3modal/blob/30f4bd48ff905b9000ca72710ea85b3ea9d7c180/packages/scaffold/src/views/w3m-connect-view/index.ts#L193), when the count of wallets available is less than 10. What would we prefer here in this scenario where count < 10, just showing the raw count N rather than the N+ syntax? Would love to tackle this to understand the contribution process better.

```js
const roundedCount = Math.floor(ApiController.state.count / 10) * 10
```

**Comment by glitch-txs** [comment]
good catch @saintmaxi , feel free to open a PR and tag me there and I'll send it to our lead dev. Thanks 🤝

**Comment by saintmaxi** [comment]
@glitch-txs Opened the PR since it's a pretty simple change, not sure how to test things out locally.
