### ISSUE TITLE
Out of gas for DAI payment handled as success

### ISSUE THREAD

**Issue by ligi** [WalletConnect/web3modal#161]
relaying this from internal QA in a project that uses web3modal.

> I elected to purchase the ticket with Dai using Metamask. I accepted the Metamask prompts to transfer, however I did not have enough ETH in my wallet to pay for gas. The UI however said the transaction was successful, while it actually failed. That resulted in an error message - that did however allow me to go back to pay again.
> 
> Request that was a "success" but actually failed due to "out of gas".

![image](https://user-images.githubusercontent.com/111600/82110728-cd857c80-9740-11ea-987f-10ea18e1bc3e.png)

I guess the gas estimation failed - not sure if this is in the domain of MetaMask or Web3Modal - hope @pedrouid can have a look here.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
