### ISSUE TITLE
Unable to integrate web3 with drizzle

### ISSUE THREAD

**Issue by raashidjunaid1** [WalletConnect/web3modal#164]
Hi there, I am trying to use web3modal pointing to local blockchain (truffle develop).

Steps to recreate:
 * `npx truffle unbox drizzle`
 * Follow the instructions on https://github.com/Web3Modal/web3modal to connect to any provider
 * Use that provider as custom provider when instantiating drizzle

Would be very grateful if anyone could help!

**Comment by pedrouid** [comment]
Is drizzle a frontend framework?

**Comment by raashidjunaid1** [comment]
Yep: https://www.trufflesuite.com/drizzle

**Comment by pedrouid** [comment]
Could you help on this issue? I'm not too familiar with all Truffle tools cc @miohtama

**Comment by raashidjunaid1** [comment]
apologies, its not a framework but just a library on top of react. Which pretty much auto syncs block data to your app

**Comment by Raghees-butt** [comment]
@raashidjunaid1 I have run to similar problem did you find anything ?

**Comment by kombos** [comment]
may i know what is the custom provider object that you are passing to the web3 section of the 'drizzle options'? Try this: 
1. do NOT forward this provider object of web3modal: 
`const provider = await web3Modal.connect();`
2. instead forward the provider object of web3 after creating a web3 object from web3modal: 
```
const web3ModalProvider = await web3Modal.connect();
const web3 = new Web3(provider);
const provider = web3.currentProvider();
```
now forward this provider object as the custom provider. not sure if it will work but do try and post the results? tx.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
