### ISSUE TITLE
Hangs on connect

### ISSUE THREAD

**Issue by nazariyv** [WalletConnect/web3modal#184]
For me on the latest Chrome (85.0.4183.83 (Official Build) (64-bit)) and Brave, it hangs on the await connect line. But only on Pop OS (Pop!_OS 20.04 LTS) (on my Mac it works fine)

`web3modal@^1.9.0`

```
const providerOptions = {
  torus: {
    package: Torus,
    options: {
      networkParams: {
        chainId: 1,
        networkId: 1,
      },
    },
  },
};

const web3Modal = new Web3Modal({
  network: "mainnet",
  // cacheProvider: true,
  providerOptions,
});

const provider = await web3Modal.connect();
```

**Comment by nazariyv** [comment]
there is some interference with providerOptions, if that line is commented out, then it doesn't hang and just connects with metamask

**Comment by nazariyv** [comment]
cookies are all enabled

**Comment by pedrouid** [comment]
cc @chaitanyapotti

**Comment by chaitanyapotti** [comment]
@nazariyv can you reach out to us on https://t.me/torusdev

**Comment by nazariyv** [comment]
will do. for now I have just avoided this issue by not using Torus

**Comment by mtsalenc** [comment]
I am facing this issue too with the following providerOptions:
```
providerOptions: {
      walletconnect: {
        package: WalletConnectWeb3Provider,
        options: {
          infuraId,
        },
      },
      authereum: {
        package: Authereum,
      },
      unilogin: {
        package: UniLoginProvider,
      },
    },
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
