### ISSUE TITLE
[bug] Connection Declined if User uses Rabby but sets preference to "Ban Rabby and use Metamask"

### ISSUE THREAD

**Issue by Mixelated** [WalletConnect/web3modal#1883]
### Link to minimal reproducible example

- any setup using web3modal in combination with injected provider

### Summary

Connection Declines on web3modal  if user installs rabby wallet but sets preference to "ban rabby and use metamask" . The expected behaviour is that the dapp communicates with metamask instead of rabby. Web3modal seems to completely reject the request

### List of related npm package versions

 "@wagmi/core": "^1.4.13"
"@web3modal/wagmi": "^3.5.6"

**Comment by glitch-txs** [comment]
that configuration is not relevant for Web3Modal because it works with EIP-6963. If you want to connect to MetaMask the button will automatically show the same way for Rabby or other wallets.
Being said this, I tested with this config and I was able to connect with both Rabby and MetaMask, you can try here: https://web3modal.com/
