### ISSUE TITLE
Connect does not return provider

### ISSUE THREAD

**Issue by ernaneluis** [WalletConnect/web3modal#198]
After I click on Metamask, modal does not disappear, also does not return any error, neither log, only this warning:

```
MetaMask: 'ethereum.enable()' is deprecated and may be removed in the future. Please use the 'eth_requestAccounts' RPC method instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1102
```

**Code:**

```
  const web3Modal = new Web3Modal({
    network: process.env.REACT_APP_ETHEREUM_NETWORK,
    cacheProvider: true,
    providerOptions: {
      walletconnect: {
        package: WalletConnectProvider,
        options: {
          infuraId: process.env.REACT_APP_INFURA_ID,
        },
      },
    },
  });

console.log('onConnect');
const provider = await web3Modal.connect();
console.log({ provider });  // this is never reached
```

**Package.json:**
```
    "web3modal": "^1.9.1",
   "web3": "^1.3.0",
    "@walletconnect/web3-provider": "^1.2.2",
```

**Comment by mtsalenc** [comment]
I'm also experiencing this. Any solution?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
