### ISSUE TITLE
Do not check for injected provider until `connect` is called.

### ISSUE THREAD

**Issue by MicahZoltu** [WalletConnect/web3modal#203]
Some providers, particularly those that are privacy friendly, will not inject on page load but instead will inject sometime after page load when the user takes some action to trigger the injection.  Unfortunately, as soon as you do `new Core()` this library will check for an injected provider and effectively memoize the result, never checking again.  This means when a user of the library calls `.connect()` or instantiates the react component you will see no inejected provider despite there maybe being one at that time.

Proposed Resolution: Remove the injection check until `.connect()` or put the checks in the React component (which will get executed every time the component is rerendered).

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
