### ISSUE TITLE
Example does not build on a fresh clone. 1.9.2

### ISSUE THREAD

**Issue by JUDOKICK** [WalletConnect/web3modal#209]
Just tried to compile, build and run the example on a fresh clone.

There is a failure with the deps somewhere.

What is the last known working node version with this repo ? Tried on 14 and 10

What is the correct steps to build and run the demo locally ?

**Comment by shalaquiana** [comment]
modified version that works on clone & install https://github.com/shalaquiana/web3modal-react-example

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
