### ISSUE TITLE
Failing to detect injected wallet on PC browser (Chrome and Brave)

### ISSUE THREAD

**Issue by makoto** [WalletConnect/web3modal#215]
I integrated web3 modal on http://app.ens.domains and the user reported that no metamask option comes up.

![web3modal](https://user-images.githubusercontent.com/2630/101622741-59c5fc80-3a0f-11eb-8d46-e57b2c8cbab6.jpeg)

https://twitter.com/taka4198aq/status/1336626050906779648

We use version 1.9.1 and this is [the config option](https://github.com/ensdomains/ens-app/blob/dev/src/api/web3modal.js#L16)

**Comment by brantlymillegan** [comment]
Here's another person having the same problem: https://twitter.com/th3_emerald/status/1336784506095718400

**Comment by crisgarner** [comment]
> I integrated web3 modal on http://app.ens.domains and the user reported that no metamask option comes up.
> 
> ![web3modal](https://user-images.githubusercontent.com/2630/101622741-59c5fc80-3a0f-11eb-8d46-e57b2c8cbab6.jpeg)
> 
> https://twitter.com/taka4198aq/status/1336626050906779648
> 
> We use version 1.9.1 and this is [the config option](https://github.com/ensdomains/ens-app/blob/dev/src/api/web3modal.js#L16)

Why does it show Nifty? I'm using Brave and it shows the Metamask wallet

**Comment by makoto** [comment]
@crisgarner can you connect via injected wallet via Nifty? I was under the impression that it just doesn't show injected option, not that it's showing nifty as a wrong one.

**Comment by crisgarner** [comment]
@makoto Usually the Injected provider is shown only in one box, meaning that you won't see dapper, metamask, nifty, or brave. Most dapps have bugs when you have multiple web3 injected providers active at the same time, might be the case of this.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
