### ISSUE TITLE
Doesn't connect in MetaMask Mobile app on Android

### ISSUE THREAD

**Issue by brantlymillegan** [WalletConnect/web3modal#217]
It doesn't connect, and there's no option that would connect

![0b67b544-0ae2-465a-9835-ff56b04873b2](https://user-images.githubusercontent.com/30162762/101694336-32cbf280-3a30-11eb-92f2-4e7c9eb94ebe.jpg)

**Comment by jamesmorgan** [comment]
I also see this problem - not sure of a solution (iOS and Android)

**Comment by nsldlr** [comment]
+1.  is this seriously broken or are we doing stuff wrong

**Comment by brantlymillegan** [comment]
Not sure what changed but I just tried it again and it's working now! So i
guess close the issue, thanks

**Comment by NullQubit** [comment]
Don't close the issue please - it still persists on iOS and Android.  Metamask opens, I accept the authentication, go back to the website and it's still not connected.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
