### ISSUE TITLE
cacheProvider false is ignored if it was set to true once before

### ISSUE THREAD

**Issue by PeterTheOne** [WalletConnect/web3modal#223]
`cacheProvider: false` only seems to control if a provider should be cached or not and not if a already cached provider should be used. If one is already cached and `cacheProvider: false` then web3modal will still use the cached provider. This is super confusing! I think it is the source of some other connection issues here on github.

I would recommend to ignore cached providers when `cacheProvider: false`.

**Comment by gwendall** [comment]
+1

**Comment by Tinh96nb** [comment]
+1

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
