### ISSUE TITLE
Wallet Connect Network Change - wrong event triggered.

### ISSUE THREAD

**Issue by ochikov** [WalletConnect/web3modal#227]
Connecting with Wallet Connect:
App: RainBow
Platform: IOS

**Issue**:
Changing network from Rainbow app triggers `on("accountsChanged")` event instead of `on("networkChanged")` event. 

<img width="575" alt="Screenshot 2021-01-13 at 15 59 59" src="https://user-images.githubusercontent.com/13587218/104461786-71694580-55b8-11eb-8c45-3271ef7cabb5.png">

**Expected Behaviour:**
Changing network from Rainbow app triggering   `on("networkChanged")` event

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
