### ISSUE TITLE
After clearCachedProvider, the subscription for the events are still triggered

### ISSUE THREAD

**Issue by ochikov** [WalletConnect/web3modal#228]
I am clearing cache provider with clearCachedProvider() function, but after that, if there is an account change, the event is triggered. How to disconnect/unsubscribe programmatically ?

**Comment by Tinh96nb** [comment]
+1

**Comment by sayhicoelho** [comment]
For now, all we have is a hack:

Check if the events is already subscribed before subscribing to it.

```js
let eventInitialized = false

function initEvents() {
  provider.on(...)
  provider.on(...)

  eventInitialized = true
}

web3modal.connect()
  .then(provider => {
    web3.setProvider(provider)

    if (!eventInitialized) {
      initEvents()
    }
  })
```

**Comment by zfogg** [comment]
+1

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
