### ISSUE TITLE
Authereum, Walletconnect and MEW connect aren't working following instructions

### ISSUE THREAD

**Issue by startpage-finance** [WalletConnect/web3modal#238]
I was able to get MetaMask, Torus, Portis and Fortmatic working.

Authereum results in the error: "Class extends value undefined is not a constructor or null|". Following instructions on: https://github.com/Web3Modal/web3modal/blob/master/docs/providers/authereum.md 

WalletConnect and MEWConnect both result in "global is undefined errors". I tried several polyfills to resolve the matter, but couldn't get it to work. Following instructions on: https://github.com/Web3Modal/web3modal/blob/master/docs/providers/walletconnect.md and https://github.com/Web3Modal/web3modal/blob/master/docs/providers/mewconnect.md

As mentioned, I was able to get  MetaMask, Torus, Portis and Fortmatic working. I'm using Angular 11, and (perhaps relevant) the ethers.js library.

**Comment by jefflam** [comment]
Having the same issue using VueJS as well..

**Comment by BernardoSM** [comment]
Hi @startpage-finance @jefflam, you probably need to add node polyfills to your app:

Webpack5: https://github.com/Richienb/node-polyfill-webpack-plugin

Vue 3 + Vite: https://github.com/voracious/vite-plugin-node-polyfills

Vue 3 + Vite example:
```javascript
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
  plugins: [
    nodePolyfills({
      protocolImports: true,
    }),
  ],
});
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
