### ISSUE TITLE
Can't connect to new metamask account once a previous account is connected?

### ISSUE THREAD

**Issue by Schwartz10** [WalletConnect/web3modal#255]
Hi there! Right now I'm working on an application where the user would probably want to connect and use more than 1 account.

Right now, when I toggle `modal.connect()`, the returned MetaMask provider seems to _always_ be the last connected account, rather than providing the user an option to connect a new account. Am i doing something wrong?

**Comment by hpolthof** [comment]
Having the same issue. Anyone got a solution for it?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
