### ISSUE TITLE
OnDemand providers

### ISSUE THREAD

**Issue by gbreux** [WalletConnect/web3modal#267]
Hi there  👋

Would it be possible to load the package of the provider asynchronously and on demand?

Something like this:

```
walletconnect: {
	package: import("@walletconnect/web3-provider"),
	options: {
		infuraId,
	},
},
```

So when people click on the walletconnect logo, it load the lib and display the QR code.

Providers packages are insanely heavy (from 150kb gzipped to 600kb) and user only need one of them, it's too bad we ask them to download them all.

What do you think?

**Comment by LeonmanRolls** [comment]
Agreed this can cause the js bundle to get into the MBs range easily

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
