### ISSUE TITLE
[bug] Disconnect when refresh in Angular 18 and @web3modal/wagmi

### ISSUE THREAD

**Issue by rtomas** [WalletConnect/web3modal#2731]
### Link to minimal reproducible example

https://github.com/vanyasav/web3modal-wagmi-angular-example

### Summary

+ Wallet is disconnected after page reload
+ Frequently failing to disconnect.

https://github.com/user-attachments/assets/cb240e31-538d-47c9-b3a7-13f9a6753252

![image](https://github.com/user-attachments/assets/bfafa763-57fc-442b-afb9-771339b20342)
(failed to disconnect with no errors on console)

### List of related npm package versions
"@web3modal/wagmi": "5.0.11"
Reported by @vanyasav

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-906/[bug]-disconnect-when-refresh-in-angular-18-and-web3modalwagmi

**Comment by francotc** [comment]
I suggest you changing `eventCoalescing` to `false` in `app.config.ts` as it looks to be an issue with the change detection.

**Comment by vanyasav** [comment]
Did it work for you? Nothing has changed for me..

**Comment by francotc** [comment]
I was checking your example and I suggest you the following changes:
* Your app is not working because you're not calling `reconnect()`, I suggest you waiting for the response of it `      reconnect(config).then(() => this.loading = true);` or something like that so you enable the button once wagmi is reconnected (this should fix it)
* I suggest you changing the main ts to `bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err))
` instead og `platformBrowserDynamic` and make the app standalone
* I suggest you using the webComponents of the library, you only have to add `CUSTOM_ELEMENTS_SCHEMA` in schemas within the component decorator
* I checked and the reconnect method is taking around 4/4sec in your project, in mine it's taking around 600ms, even with the same RPC so I don't know what's going on there.
* Finally Ethers have a faster reconnect but I wasn't able to access to the provider once using the wallet, seems the documentation been updated or they forget to expose the methos

Hope it help

**Comment by rtomas** [comment]
Thanks @francotc 

Please follow the docs -> https://docs.walletconnect.com/appkit/javascript/core/installation

and don't forget to add `reconnect()`

**Comment by francotc** [comment]
Thanks for the response Tomas, with Wagmi I was able to use it. But on Ethers, it's not working with the instructions provied.

**Comment by rtomas** [comment]
@francotc do you have a minimal reproducible example to share with me ?

**Comment by vanyasav** [comment]
> I was checking your example and I suggest you the following changes:
> 
> * Your app is not working because you're not calling `reconnect()`, I suggest you waiting for the response of it `      reconnect(config).then(() => this.loading = true);` or something like that so you enable the button once wagmi is reconnected (this should fix it)
> * I suggest you changing the main ts to `bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err)) ` instead og `platformBrowserDynamic` and make the app standalone
> * I suggest you using the webComponents of the library, you only have to add `CUSTOM_ELEMENTS_SCHEMA` in schemas within the component decorator
> * I checked and the reconnect method is taking around 4/4sec in your project, in mine it's taking around 600ms, even with the same RPC so I don't know what's going on there.
> * Finally Ethers have a faster reconnect but I wasn't able to access to the provider once using the wallet, seems the documentation been updated or they forget to expose the methos
> 
> Hope it help

Thanks! Reconnect was the problem, and II guess I can live with 4 seconds load time, howewer it's not ideal.
