### ISSUE TITLE
Cached Provider error

### ISSUE THREAD

**Issue by nithronium** [WalletConnect/web3modal#274]
EDIT: Steps to reproduce added;

1. Open any website where Web3modal is loaded
2. Open console on browser
3. Paste the following script, choose metamask from providers and when popup opens, reject connection

```
try {
			provider = await web3Modal.connect();
		} catch(e) {
			alert(e);
		}
```
You will see that Metamask itself throws an error but Web3modal doesn't throw one, it alerts "undefined". In my case, the issue wasn't related to user rejecting simply because they were already on Metamask in-app browser and was already connected. But still, no reason why error happens. Catcher can't catch error.

---- Original Message ----

Greetings,

I am using the latest distribution of Web3Modal library. On my init function I have;

```
web3Modal = new Web3Modal({
        cacheProvider: true,
        providerOptions,
        disableInjectedProvider: false,
    });
```

So I am caching the provider. On different pages (in order not to make user wallet connect every time) I use a script;

```
if(web3Modal.cachedProvider !== "") {
    try {
        provider = await web3Modal.connect();
    } catch(e) {
        alert('error');
    }
}
```

So far I have tested the Dapp on many different browsers and in-app browser on metamask. Had issue on only one device with Android and metamask latest. It would return the "error" message to the user's screen. However, when I use `alert(e)` or any type of error reporting, it returns `undefined`.

Is there a way to see the error on the cached provider? 

The device specs;

Metamask v2.2.0 (latest)
Redmi Note 8 Pro
Android 10 QP1A

**Comment by johnfrades** [comment]
Bump i have the same problem, cant catch the errors

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
