### ISSUE TITLE
chainChanged event not detected with WalletConnect

### ISSUE THREAD

**Issue by RiccardoBiosas** [WalletConnect/web3modal#275]
When using metamask through the web3Modal walletconnect provider, if I change the network on metamask after successfully connecting to the dapp the client does not appear to detect the ```chainChanged``` event.
```
// Subscribe to chainId change
provider.on("chainChanged", (chainId: number) => {
  console.log(chainId);
});
```

**Comment by acrens** [comment]
How to solve this problem？

**Comment by HasnainAsif** [comment]
I have tried networkChanged event too, but it only works when I change my wallet address and always gives undefined value.
If anyone know any solution can you please help.

**Comment by Deokti** [comment]
`connector.on("session_update", () => {});` doesn't work also

**Comment by Deokti** [comment]
https://github.com/MetaMask/metamask-mobile/issues/2927

**Comment by moahammadalt** [comment]
Same issue over here.

**Comment by mburger81** [comment]
Do you use ethers or web3js?

The web3js seems to have the events, but not ethers

**Comment by HasnainAsif** [comment]
We are using web3js

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
