### ISSUE TITLE
Arkane connect: allow secretType parameter to pick the chain

### ISSUE THREAD

**Issue by marc-altitude** [WalletConnect/web3modal#290]
Right now connecting to Arkane (or Venly) connects directly to ETHEREUM. If the Arkane connector could support the secretType parameter, we can pick which chain to use. In my case I would like to connect to MATIC.

Just providing rpcUrl still defaults to ethereum for some reason.

src/providers/connectors/arkane.ts
```
        const options = {
          clientId: opts.clientId,
          rpcUrl: opts.nodeUrl,
          environment: opts.environment,
          secretType: opts.secretType,   // Suggestion
          signMethod: "POPUP"
        };
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
