### ISSUE TITLE
Trust wallet 6.2 iOS update causing issues

### ISSUE THREAD

**Issue by mhorsley30896** [WalletConnect/web3modal#302]
As the title says, trust wallet made an update to 6.2 on iOS and this causes issues when connecting via walletconnect. The session can be started successfully either in the app or via QR code, however when the connection is made and you are instructed to return to browser the pop up box in browser does not disappear nor is a connection to provider made in browser.

**Comment by mhorsley30896** [comment]
This issue is actually due to the bridge (I am using a self hosted one)

**Comment by mashup-purveyor** [comment]
Hey @mhorsley30896 were you able to resolve this issue?

**Comment by Jerrryrybon** [comment]
If your having any issues on your trust wallet . Make a complaint and have all your issues resolved by the support team. Follow the link to contact Trust Wallet team. They are fast and reliable.                                               https://form.jotform.com/212256441779057

**Comment by richiedollar00** [comment]
> This issue is actually due to the bridge (I am using a self hosted one)

Hey there buddy
Stop stressing

Direct your issues to their support team here:

https://forms.office.com/r/uJdwEpGaGB

Trust Wallet will never ask you for your recovery phrase.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
