### ISSUE TITLE
correct flow

### ISSUE THREAD

**Issue by xale76** [WalletConnect/web3modal#310]
Hello, I'm wondering what I'm missing.
I figure this kind of flow:

on entering my website, Web3Modal should check if is there any provider cached and

a) in case of provider cached it should check if the wallet is still connected to the provider
     a.1) in case of yes, Web3Modal should return web3 object and prompt nothing, the website could start regularly (my website 
              will show the address the wallet is connected with somewhere on UI)
     a.2) in case of no, Web3Modal should clear cached provider and do nothing waiting for user to click on "connect" and show 
              popup (my website will show "connect" instead of address)
b) in case of none provider cached, web3modal should do nothing waiting for user to click on "connect" and show popup

How to achieve this? I'm fighting with it from days, without success.

I use web3, react, and in particular I'd like to create a general function to be used everywhere in the website (everypage will handle this process, and I would like to write once the code).

This is my web3modal configuration

const providerOptions = {
  /* See Provider Options Section */
  metamask: {
      display: {
      logo:     <IMG>
      name: "Metamask or other browser Wallet",
        description: "Connect with the provider in your Browser"
      },
      package: detectEthereumProvider
    },
  walletconnect: {
      display: {
        name: "Wallet Connect"
      },
      package: WalletConnectProvider,
      options: {
        rpc: {
            4: <RINKEBY INFURA LINK>,
            1337: "http://127.0.0.1:7545",
            // ...
          },
      }
    }
};

const web3Modal = new Web3Modal({
     cacheProvider: true, // optional
     providerOptions, // required
     disableInjectedProvider: false, // optional. For MetaMask / Brave / Opera.
});

thank you

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
