### ISSUE TITLE
Modal wont launch in mobile viewports in Opera Browsers

### ISSUE THREAD

**Issue by AlfieDarko** [WalletConnect/web3modal#311]
Hey all, raising an issue here.

When trying to load the modal, it doesn't launch in mobile viewports when using the opera browser on desktop nor the opera browser on mobile iOS. 

This is observable both on the web3modal.com demo site and my personal projects.

**OS:**
macOS Big Sur v.11.3

**Browser:** 
**Desktop:** Version:78.0.4093.147 (x86_64)
**Mobile:** Opera Mobile iOS: (Latest version)

**_Instructions to reproduce._**

**1]** Open Opera
**2a]** If using the desktop version,  choose a mobile viewport in the browser console, then proceed to [2]
**2b]** If using Opera Mobile on proceed to next step
**3]** Navigate to web3modal.com
**4]** Click Connect
**5]** You should observe that the modal doesn't pop up on the browsers in mobile viewports.

This is shown the the browser console too.
![Screenshot 2021-08-18 at 16 52 10](https://user-images.githubusercontent.com/17105269/129930517-ec0d20d8-2dd8-4b03-bb83-2f1842268863.png)

Not quite sure, ill investigate further but not too sure how far I can get with it.

Thanks,

Alfie

**Comment by AlfieDarko** [comment]
After further looking into the web3Modal react components to see deeper how the component works, i see that there is a function 'updateWeb3Modal' on the window object that when called, causes the component state to be updated and thus shown on screen. So in these Opera mobile viewports, Im able to trigger it manually by calling

`window.updateWeb3Modal({
  show: true,
  lightboxOffset: 1,
})`

in the browser console. It then shows:

![Screenshot 2021-08-18 at 16 50 38](https://user-images.githubusercontent.com/17105269/129930275-1ac3116c-a57b-49d8-adc9-abc4be2f05a1.png)

Is the web3Modal being created with no provider information in this way? Still midway investigation but anyone that knows abit more about the internal workings of the component, any help would be appreciated!

**Comment by swisscantons** [comment]
no news on this issue?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
