### ISSUE TITLE
How to dynamically switch between networks?

### ISSUE THREAD

**Issue by iturizam** [WalletConnect/web3modal#313]
I have a cross-chain BSC and ETH app, I use Injected and WalletConnect providers/connectors.
Is there a way to switch wallet network/chain dynamically on WalletConnect using TrustWallet for example?

**Comment by PiatKox** [comment]
I have the same problem. Did you resolve it?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
