### ISSUE TITLE
Your vanilla JS example doesn't work when using Fortmatic

### ISSUE THREAD

**Issue by 4skinSkywalker** [WalletConnect/web3modal#314]
It throws the following error: **Uncaught (in promise) TypeError: provider.on is not a function at HTMLButtonElement.onConnect (example.js:171)**

![image](https://user-images.githubusercontent.com/17194393/130637128-2e74bb14-6025-4b1e-9360-caa542fa45b8.png)

**Comment by wpitallo** [comment]
I am getting the same error

**Comment by MariusMez** [comment]
Hi any idea how to solve this ?

**Comment by MrsBookik** [comment]
same here

**Comment by itinance** [comment]
Formatic seems to break the Provider-interface with a different structure of methods

**Comment by Lovelogist-1st** [comment]
Any solution to this pls?

**Comment by matejdrazic** [comment]
Any update on this?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
