### ISSUE TITLE
Add binance testnet

### ISSUE THREAD

**Issue by rasti8** [WalletConnect/web3modal#321]
Hi, I was trying to use binance testnet in the providerOptions like this: 
```
const providerOptions = {
    walletconnect: {
      package: WalletConnectProvider,
      options: {
        rpc: {
          97: "https://data-seed-prebsc-1-s1.binance.org:8545/",
        },
        network: "binance-testnet",
      },
    },
  };
```

But then I saw that this constant is still not in the master branch https://github.com/Web3Modal/web3modal/pull/237. Can you please add it to it?

**Comment by rithgan** [comment]
Any update on this? I would also like it to be added as a provider

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
