### ISSUE TITLE
not working with walletconnect

### ISSUE THREAD

**Issue by xale76** [WalletConnect/web3modal#324]
Hello, this is my configuration 

const providerOptions = {
  walletconnect: {
      display: {
        name: "Wallet Connect"
      },
      package: WalletConnectProvider,
      options: {
        infuraId: "xxxxx",
       
      }
    }
};

....

provider = await web3Modal.connect();
web3 = new Web3(provider);
....

after connection every contract interaction remains pending in await (i'm trying with rinkeby network)

in example

`await dai.methods.approve(addr,amnt).send({from:address});`

On my wallet (in this case metamask on android) I confirm the approval, the transaction is completed with success, but my react code not moving from await (not throwing any error, my piece of code in try catch)

What's the problem?

**Comment by patniemeyer** [comment]
WalletConnect recently announced a 2.0 version that uses API keys.  I'm not sure if their original bridge is still working.  By the way, the web3modal.com demo has never worked properly with walletconnect as far as I can tell.

**Comment by felipelincoln** [comment]
Same problem.
Did you find a solution for this @xale76 ?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
