### ISSUE TITLE
Cookies Issue

### ISSUE THREAD

**Issue by leykun10** [WalletConnect/web3modal#325]
wallet connect stores cookies and does not allow to sign with other account or the qr modal wont pop up after first sign up.
the method web3Modal.clearCachedProvider(); does not clear the cookies.
any solutions with out manually clearing the cookies?

**Comment by 4skinSkywalker** [comment]
Hi @leykun10,

`clearCachedProvider()` acts both on the `cachedProvider` property of the `web3Modal` instance and the entry `WEB3_CONNECT_CACHED_PROVIDER` in the localStorage.

That said if you want to do it manually-ish:
```js
web3Modal.cachedProvider = ""; // This is referring to your instance not the class
Web3Modal.removeLocal(Web3Modal.CACHED_PROVIDER_KEY); // These are both referring to the class not your instance
```

Or more manually:
```js
web3Modal.cachedProvider = ""; // This is referring to your instance not the class
localStorage.removeItem("WEB3_CONNECT_CACHED_PROVIDER");
```

Thanks,
Fredo

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
