### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by OneEyeDoll** [WalletConnect/web3modal#331]
Hello, i followed the VanillaJS example guide. And everything works fine on Desktop, but not on mobile. This is my current code.

`try {
        web3Modal = new Web3Modal({
            network: "binance", // replace mainnet to binance
            providerOptions, // required
            disableInjectedProvider: false, // optional. For MetaMask / Brave / Opera.
        });        
            console.log(web3Modal)
            try {
                web3Modal.resetState()
                provider = await web3Modal.connect();
                console.log(provider)
            } catch(e) {
                console.log("Could not get a wallet connection", e);
                return;
            }
`

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
