### ISSUE TITLE
How to disable click after choosing provider?

### ISSUE THREAD

**Issue by fahadh4ilyas** [WalletConnect/web3modal#343]
After selecting one provider, the user can still select another provider before the provider's pop-up showed up because the provider's pop-up takes quite a long time to load. This result multiple providers can be selected even though the fastest provider will be accepted.

Here is the example

![image](https://user-images.githubusercontent.com/37577369/141235905-5072fc5b-ca93-4250-b304-af5e03f27a90.png)

Is there any way to disable click even outside the modal after selecting one of the providers?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
