### ISSUE TITLE
Web3 

### ISSUE THREAD

**Issue by JacopoNeroni** [WalletConnect/web3modal#347]
With React Native Expo V4.13.0, importing the web3 V1.6.1 module, I get the following error:

`Unable to resolve module crypto from /Users/black/Desktop/test/node_modules/web3-eth-accounts/lib/index.js: crypto could not be found within the project or in these directories:
  node_modules/web3-eth-accounts/node_modules
  node_modules
  ../../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  24 | var Method = require('web3-core-method');
  25 | var Account = require('eth-lib/lib/account');
> 26 | var cryp = (typeof global === 'undefined') ? require('crypto-browserify') : require('crypto');
     |                                                                                      ^
  27 | var scrypt = require('scrypt-js');
  28 | var uuid = require('uuid');
  29 | var utils = require('web3-utils');`

Yesterday I updated the version of expo and it no longer worked, before it worked fine.

Does anyone have the same problem?

**Comment by repinsky13** [comment]
Had a similar problem with my react project before, I think it has to do with the fact that current version of webpack doesn't automatically polyfill node modules into the bundle. So try looking up the instructions on how to manually configure webpack to polyfill the modules you're missing (crypto in your case) and see if the problem persists - it helped me with a similar problem earlier

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
