### ISSUE TITLE
clearCachedProvider doesn't remove `walletconnect` localStorage (auto signs-in last WC acct)

### ISSUE THREAD

**Issue by evvvritt** [WalletConnect/web3modal#354]
Hi,
Even with `cachedProvder: false` clicking WC will auto-sign-in the previous account because the `walletconnect` `localStorage` item is still present.

Would be a nice improvement not to have to do that manually :)

Thanks for developing this modal!

**Comment by theshadowagent** [comment]
Please fix this

**Comment by mrguamos** [comment]
try this 

```localStorage.removeItem('walletconnect')```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
