### ISSUE TITLE
JS errors now encountered on Opera

### ISSUE THREAD

**Issue by paulfros** [WalletConnect/web3modal#355]
Testing here: https://web3modal.com/
With browser version: 82.0.4227.23 (x86_64) on Opera on a Mac
Results in JS error: "Uncaught (in promise) undefined"
After clicking on "Opera" in the Modal.

Same problem observed in Windows Opera 82.0.4227.23.

Also web3 apps, like https://app.ens.domains, no longer successfully connect.
They show other JS errors like in the browser console like: "setup error:  TypeError: Cannot read properties of undefined (reading 'message')"

**Comment by mirshko** [comment]
This also occurs when using Dapper Wallet.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
