### ISSUE TITLE
Frame not working.

### ISSUE THREAD

**Issue by ACollectionOfAtoms** [WalletConnect/web3modal#361]
When trying to use Frame as described in the documentation at https://github.com/Web3Modal/web3modal/blob/master/docs/providers/frame.md, Frame does not show up in the modal.

Anyone else having this issue?
```json
"web3modal": "^1.9.4"
"eth-provider": "^0.9.8"
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
