### ISSUE TITLE
Cancelling switch network prompt after adding chain does not throw error for MetaMask

### ISSUE THREAD

**Issue by holic** [WalletConnect/web3modal#363]
The following description is for usage with MetaMask. I'm not sure if this is a MetaMask issue or an issue with how web3modal communicates with MetaMask.

When you call `wallet_switchEthereumChain` and hit cancel in MetaMask (to reject the request), the following error is thrown:
> MetaMask - RPC Error: User rejected the request. 

Similarly, when you call `wallet_addEthereumChain` and hit cancel in MetaMask (to reject the request), you also get the following error:
> MetaMask - RPC Error: User rejected the request.

However, `wallet_addEthereumChain` has a secondary step that is equivalent to `wallet_switchEthereumChain`. Calling this first prompts to add the network/chain, then after it's added it prompts you to switch to that network.

If you cancel the switch prompt after confirming the additional network/chain config, nothing happens. No error is thrown and the function call returns.

For my particular use case, I am sending a transaction immediately after. If the user is on the wrong chain when sending that transaction, they may be throwing gas fees to the miners for nothing.

I can work around this by checking the current network immediately after the call to `wallet_addEthereumChain`, but I would expect an error thrown like `wallet_switchEthereumChain` does when cancelling the request to switch networks.

**Comment by holic** [comment]
Just ran through these reproduction steps with https://github.com/NoahZinsmeister/web3-react and that seemed to do the right thing. Cancelling the network switch request after adding a network returns/throws the "user rejected" error.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
