### ISSUE TITLE
Venly

### ISSUE THREAD

**Issue by jdwinters** [WalletConnect/web3modal#366]
Is there any documentation for integrating Venly as a provider? I know there's this link below here, but it's not well documented.

https://demo.arkane.network/pages/web3modal

**Comment by Lucabudi** [comment]
Hei, i'm lookin for a solution too, it's look like the documentation is not working with Venly, did you find out something?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
