### ISSUE TITLE
web3modal.connect() catches `undefined` as errors

### ISSUE THREAD

**Issue by johnfrades** [WalletConnect/web3modal#378]
so if the user rejects connecting to metamask
![image](https://user-images.githubusercontent.com/20201069/148632048-c369f976-96a0-4f56-bb0d-ec7f36e38dbd.png)

and if theres a pending request and user tries to connect 
![image](https://user-images.githubusercontent.com/20201069/148632058-98bbd880-9a4b-4e54-a715-256fc522ed41.png)

All of them catches the error but its always undefined. so its quite hard to see what kind of error it throws. is there a way around this?

**Comment by stasionok** [comment]
Same trouble. I can`t handle errors from metamask respectively message

**Comment by german-schneck** [comment]
+1

**Comment by cfiestas6** [comment]
same here

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
