### ISSUE TITLE
MetaMask option not initiating Chrome Extension 

### ISSUE THREAD

**Issue by jordanlesich** [WalletConnect/web3modal#380]
Some of our users are noticing that the metamask button on the web3 modal does not do anything when we hit it. 

This is non-deterministic, as about 70% of the time it works. 

Steps to reproduce: 
- delete Web3Modal local storage
- close browser
- reopen app again 
- call requestProvider (button)
- click on metamask option. 

 Important things to note: 
 - Our app deletes sessionStorage on page reload. 
 - Our app does not call the requestProvider more than needed. 
 - Our app did have more than one instantiation of the provider (we had a default), but removing it had no effect on the bug itself. Some devs were having similar issues here: 
 https://github.com/Web3Modal/web3modal/issues/350
 
 Any help of insights would be greatly appreciated. Thanks!

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
