### ISSUE TITLE
Change Network

### ISSUE THREAD

**Issue by xale76** [WalletConnect/web3modal#382]
Hello!
I have this need. I am developing a decentralized bridge where the user is on the chain from which he wants to send his tokens. Once the request is made to the bridge, there is a need for the user to move to the destination chain to pick up the tokens sent from the other chain.
Is there a way for me to programmatically click on a button on my page and web3modal moves directly to the second chain without opening the wallet (in my case metamask) to perform the switch manually?

Thank you

**Comment by blabno** [comment]
```javascript
provider.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: config.chainId }],
      })
```
This does not work with Brave's built-in wallet that pretends to be MetaMask.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
