### ISSUE TITLE
How to define options (RPC, chainId, URL) for MetaMask?

### ISSUE THREAD

**Issue by MrsBookik** [WalletConnect/web3modal#383]
Although I define only _Formatic_ and _WalletConnect_ in `providerOptions`, **_MetaMask_** still appears automatically in the Web3Modal.

            web3Modal = new Web3Modal({
                network: 'matic',
                cacheProvider: false,
                providerOptions: {
                    fortmatic: {
                        package: Fortmatic, // required
                        options: {
                        },
                    },
                    walletconnect: {
                        package: WalletConnectProvider,
                        options: {
                        },
                    },
                    authereum: {
                        package: Authereum, // required
                    },

But it seems to connect with wrong or outdated RPC-URLs to Matic-Network, which I'd like to change.

1. How can I do that? In the README only other Providers are mentioned, but not MetaMask? 
2. Can I disable MetaMask?

**Comment by adiled** [comment]
This is not clear anywhere and apparently still a question mark.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
