### ISSUE TITLE
How to configure WalletConnectProvider with local network rpc

### ISSUE THREAD

**Issue by R-Santev** [WalletConnect/web3modal#390]
I am trying to set up WalletConnectProvider as a provider option of Web3Modal on the localhost ("http://localhost:8545") network.
![unknown](https://user-images.githubusercontent.com/77731162/150943451-7a0e7642-1450-45ec-8b3a-07cbbee3d20b.png)

For some reason, when I don't set the network property, the modal works but it is trying to use the Infura API
![unknown](https://user-images.githubusercontent.com/77731162/150943567-a22717f8-bf3e-4b95-956d-f1d1e6912034.png)

When I set the network property, it throws this error:
![unknown](https://user-images.githubusercontent.com/77731162/150943597-30b9812a-851e-47f8-8bcc-09e9ad9b8d2b.png)
"No chainId found match ${network}".

**Comment by R-Santev** [comment]
I found it works when using ```http://127.0.0.1:8545/``` for the ```rpc``` configuration

**Comment by wuzhengyan2015** [comment]
![2022 03 26_吴政衍 9babe24919c79346cc4f5702f069e252](https://user-images.githubusercontent.com/16127824/160231512-411e8e8b-45b8-4d2e-b2f2-386900a6ac50.png)
chainId is invalid in web3modal, you should use network param. but there is a default network list in chain.ts, you cannot use custom network.
There is a hack. I think web3modal should support chainId param.
```js
walletconnect: {
      package: WalletConnectProvider, // required
      options: {
        rpc: {
          1: "https://eth-mainnet.alchemyapi.io/v2/",
          56: "https://bsc-dataseed.binance.org/",
          137: "https://rpc-mainnet.maticvigil.com",
          421611: "your localhost"
        },
        // matic binance mainnet
        network: 'arbitrum-rinkeby'
      }
    }
```

**Comment by R-Santev** [comment]
@wuzhengyan2015 As I understood WalletConnect just does not work with http provider

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
