### ISSUE TITLE
Release 1.9.5 triggers CoinbaseWallet even if it's not configured in web3Modal

### ISSUE THREAD

**Issue by appleseed-iii** [WalletConnect/web3modal#394]
web3Modal configuration does not includes `walletLink` for CoinbaseWallet, however IF a user has Coinbase wallet when they click "Metamask" in the Web3Modal the coinbase wallet pops up IN ADDITION to Metamask wallet:

```js
const initModal = new Web3Modal({
  // network: "mainnet", // optional
  cacheProvider: true, // optional
  providerOptions: {
    walletconnect: {
      package: WalletConnectProvider,
      options: {
        rpc: {
          1: NETWORKS[1].uri(),
          4: NETWORKS[4].uri(),
          42161: NETWORKS[42161].uri(),
          421611: NETWORKS[421611].uri(),
          43113: NETWORKS[43113].uri(),
          43114: NETWORKS[43114].uri(),
        },
      },
    },
  },
});
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
