### ISSUE TITLE
Metamask Mobile Not working

### ISSUE THREAD

**Issue by Zeppe79** [WalletConnect/web3modal#396]
Hi, 

web3modal works very well with TrustWallet and with Desktop Metamask, but I can't make it work into Metamask Mobile. It just doesn't show any popup message when I call contract functions. Popups show only when I have to connect the wallet ...

**Comment by FireEth** [comment]
Ever find a solution to this?

**Comment by Zeppe79** [comment]
Switched to blocknative library, but it seems to be a metamask mobile bug with deep links

**Comment by italosantana** [comment]
Any update for this? I had the same problem here.

**Comment by alexeygorbachevskiy** [comment]
It seems not only metamask deeplinks doesn't work, but deep links at all. I also have problem with deep links -> redirect to mobile is being occured, but popup is not being opened.

**Comment by Usernamethoma** [comment]
@Zeppe79 @alexeygorbachevskiy @FireEth @italosantana We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
