### ISSUE TITLE
Error: Cannot find module 'react-dev-utils/getPublicUrlOrPath'

### ISSUE THREAD

**Issue by juliankrispel** [WalletConnect/web3modal#401]
`npm start` is currently broken because `react-dev-utils` is missing from package dependencies

**Steps to reproduce:**
1. Fresh clone of repository
2. `npm install` to install all dependencies
3. `npm run start` to run examples
4. I'd expect this to work but the process instead gets interrupted with "Error: Cannot find module 'react-dev-utils/getPublicUrlOrPath'"

![image](https://user-images.githubusercontent.com/1188186/151922227-67b05a08-af51-48be-9f71-9e0acb32e5c1.png)

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
