### ISSUE TITLE
Bitski consent error in demo website

### ISSUE THREAD

**Issue by michael-sumner** [WalletConnect/web3modal#411]
![Screenshot 2022-02-18 at 21 52 16](https://user-images.githubusercontent.com/75835774/154766221-fdfb2534-a42f-4ac8-96b9-3de70000ccc9.png)

**Comment by T-Damer** [comment]
Did you add your localhost page in the [bitski.dev](https://developer.bitski.com) config? 
![image](https://user-images.githubusercontent.com/49658988/154810627-6c189059-b9ab-43de-8c30-9d2000ab032e.png)
I've also added a `redirect.html` in the public folder of my project, but something still doesn't work (because of vite, I suppose) and I've changed this section:
![image](https://user-images.githubusercontent.com/49658988/154810662-8d0f7a04-2430-4256-9cbc-68fa5b6e49a5.png)

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
