### ISSUE TITLE
`updateTheme` is not working

### ISSUE THREAD

**Issue by T-Damer** [WalletConnect/web3modal#416]
It doesn't throw any errors, but the color doesn't change. I can change the theme when creating a new instance:
```TS
const configuredModal = new Web3Modal({
  cacheProvider: true,
  theme: 'dark',
  disableInjectedProvider: false,
  ...
```
But later, we have no access to the `theme` property, I need a quick switch

I tried updating from the page itself (after the button pressed) and tried to run this inside the `mobx` store, nothing of this did work

Maybe I am doing something not right? Do you have any examples of using this method?

**Comment by catmaxi** [comment]
yeah I've noticed this as well.

**Comment by christophercr** [comment]
Same problem here

**Comment by alonbl92456** [comment]
Doesn't work for me either, any thoughts about a workaround ?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
