### ISSUE TITLE
Duplicate modal when trying to create multiple connect button, result to bug.

### ISSUE THREAD

**Issue by pandit69** [WalletConnect/web3modal#418]
We are generating multiple connect button in a page. And it seems because of that. it create multiple instance of Web3Modal and therefore more than 1 `<div id="WEB3_CONNECT_MODAL_ID">` element.  

Will a check in renderModal, if the element already exist work?

```
private renderModal() {

    /// Check before rendering new elment
    
    const el = document.createElement("div");
    el.id = WEB3_CONNECT_MODAL_ID;
    document.body.appendChild(el);

    ReactDOM.render(
      <Modal
        themeColors={this.themeColors}
        userOptions={this.userOptions}
        onClose={this.onClose}
        resetState={this.resetState}
        lightboxOpacity={this.lightboxOpacity}
      />,
      document.getElementById(WEB3_CONNECT_MODAL_ID)
    );
  }
  ```

Upon clicking connect on 2nd connect button and choosing metamask option, the modal doesn't automatically close. It seems that it never goes beyond `const provider = await walletConnect.connect()`

```
async function handleConnect() {
    try {
      console.log('handleConnect');
      const provider = await walletConnect.connect()
      console.log('after provider');
      const web3 = new Web3(provider)
      const data = await web3.eth.getAccounts()
      ........
    } catch (e) {
      console.error('ERROR(components): AccountConnect', e)
    }
  }
  
        <button
          onClick={() => handleConnect()}
          className={styles.connectButton}
        >
          <span className={`${styles.status}`}></span>
          Connect Wallet
        </button>
  ```
  
  There is related issue with no solution https://github.com/Web3Modal/web3modal/issues/46

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
