### ISSUE TITLE
WalletConnect Sometimes Skips QR Code

### ISSUE THREAD

**Issue by quantass** [WalletConnect/web3modal#420]
After connecting to WalletConnect  the first time it is fine however the next time you try to bring up the QR code it will skip the display and go straight into ending a new transaction as if it assumes the provider already Approved the request when that wasn't the case.   I was expecting _web3.eth.sendTransaction() to display a prompt on the phone asking to approve the send transaction. Nothing appears.

clearCachedProvider(), clearSubscription(), removeAllListerners(), and disconnect() were all used before trying to web3Modal.connect() the second time around.

**Comment by vrde** [comment]
Same issue here. I ended up doing `localStorage.removeItem("walletconnect")`, that is not a very clean solution, but for the time being it works.

I would expect `clearCachedProvider` to clean up `localStorage` for me. @pedrouid what do you think :) ?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
