### ISSUE TITLE
Can't select Metamask provider after navigating back to the page

### ISSUE THREAD

**Issue by quantass** [WalletConnect/web3modal#423]
For the web, once you initialize Web3Modal (W3M) on your site but then navigate to another webpage (ie. cnn.com) then hit the BACK button, W3M will not allow you to select the Metamask provider icon within its popup dialog.

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and debug it

**Comment by walidvb** [comment]
My understanding is that it is because the implementation would typically check for `web3Modal().cachedProvider`, and therefore skip the choice window

**Comment by KiLien** [comment]
It is not recommended to create Web3Modal objects frequently, you can call it once when the page is first loaded, store the web3Modal object in pinia (Vuex), and then determine if "WEB3_CONNECT_CACHED_PROVIDER" is linked to the account, and use that to determine if you need to call the connect method

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
