### ISSUE TITLE
Build is not working on Sharehoster (localhost no problems)

### ISSUE THREAD

**Issue by filipe-te** [WalletConnect/web3modal#426]
Hallo Guys, 

i set my minting dapp all up and run it with "npm run start" everything works just perfect. 
On my Localhost:3000 I can connect with Metamask and Walletconnect on Desktop or Mobile. No problems at all. 

When I run "npm run build" and put my build on a sharehoster to get public access to my minting dapp WalletConnect wont work. 
The WalletConnect Pop up works fine and it gives my a QR-Code (like on Localhost) but after that I cant connect my Wallet with that QR-Code. It takes a few Seconds and i get "connecting failed" in my wallet.

Is there a problem with "npm run build"? Or do I need do make same changes on my sharehoster? Any Ideas? I cant find the Issue because on Localhost there is no Issue :(

**Comment by harryjia** [comment]
me too

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
