### ISSUE TITLE
Not working inside Firefox using Vercel, CSP issue

### ISSUE THREAD

**Issue by MelodicCrypter** [WalletConnect/web3modal#429]
Hi, has any of you used this with Vercel?

in the .env of create-react-app i set
`INLINE_RUNTIME_CHUNK=false`

When ran locally, like normal run, not using vercel dev, both Chrome and Firefox are working fine

But when I run `vercel dev`
Chrome working fine but on Firefox it is showing this issue:

![Screen Shot 2022-03-11 at 1 03 47 PM](https://user-images.githubusercontent.com/18341500/157805552-1e5d639f-3f57-478e-ae5b-0a512547e1aa.png)

The modal will not show at all.

This is vercel.json file looks like
```
{
  "version": 2,
  "public": false,
  "builds": [
    {
      "src": "/server/index.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "server/index.js"
    }
  ]
}
```

The server/index.js is handling all. And this is the structure
- frontend
- - - build+
- server
- - - index.js
- vercel.json

Really need some help. :) Thanks!

@pedrouid

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
