### ISSUE TITLE
Move react and react-dom to peerDependencies

### ISSUE THREAD

**Issue by Scott-Hickmann** [WalletConnect/web3modal#439]
Hi, it looks like having react and react-dom in dependencies can cause conflict with other packages with Next.js (in my case [Persona](https://www.npmjs.com/package/persona)). Moving react and react-dom to `peerDependencies` instead seems to fix the issue. Would it be possible to make that change?
```json
  "peerDependencies": {
    "react": ">= 16",
    "react-dom": ">= 16"
  },
  "dependencies": {
    "detect-browser": "^5.1.0",
    "prop-types": "^15.7.2",
    "styled-components": "^5.3.3",
    "tslib": "^1.10.0"
  }
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
