### ISSUE TITLE
Additional Components or Layouts for the Provider Grid

### ISSUE THREAD

**Issue by androolloyd** [WalletConnect/web3modal#44]
As a developer I want to be able to include Web3Connect components in a variety of ways, the Provider Grid as its own component exported would enable an easier integration experience for the multiple providers configured throughout the core, and remove the requirement to connect through providers through the modal interface.

**Comment by miohtama** [comment]
I am working on "a Angular version" of Web3modal. 

It is very difficult to customize Web3modal as it. Instead, I strive to make it possible for the developers to roll out their own widgets with ease.

**Comment by androolloyd** [comment]
i wonder if we could make them even more agnostic
since the use styledcss in components right now

**Comment by pedrouid** [comment]
The additional components is kinda tricky one to scope since it could be either too flexible to introduce to many edge cases or not flexible enough to be valuable.

I've already included Themes for changing colors with v1.2.0 which adds some customization so  I like the idea of Layouts to include a few different options for alignment and etc.

Web3Modal is built with react so Im not sure how the removal of styled-components would make it easier to customize it anyway. However I might remove styled-components to reduce bundle size.

**Comment by hackyguru** [comment]
Feedbacks addressed on W3MV2 - framework agnostic, additional components that can support the whole onboarding experience of users. Checkout the [demo](https://web3modal.pages.dev) or pull the recent changes :)
