### ISSUE TITLE
Mac Chrome Metamask Wallet is not detected

### ISSUE THREAD

**Issue by dbslone** [WalletConnect/web3modal#445]
I have the Chrome Metamask wallet connected. If I open the dev tools and type `window.ethereum` I receive an object for the response but the modal does not show Metamask connection option. To reproduce this issue you just need to use the latest version of the package with Chrome  99.0.4844.83. When I launched with Firefox the option for Metamask was displayed.

**Comment by dbslone** [comment]
![Screen Shot 2022-03-30 at 1 15 41 AM](https://user-images.githubusercontent.com/264547/160784656-07bb8bba-5427-4be1-b668-c34dd7a6ff82.png)

**Comment by valensto** [comment]
+1

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
