### ISSUE TITLE
Using web3modal with web3-react

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#446]
So does it work now?
Can we easily use web3modal with web3-react?

I tried doing something like this:

```
const web3Modal = useWeb3Modal();
const { active, account, library, activate, deactivate } = useWeb3React()
...
const provider = web3Modal.connect();
await activate(provider);
```

But I get "TypeError: connectors is not iterable"

Is there something we have to do with injectConnectors?

Any help would be greatly appreciated!

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
