### ISSUE TITLE
feat: Add support for Solana wallets like Phantom and Solflare

### ISSUE THREAD

**Issue by anoushk1234** [WalletConnect/web3modal#458]
Can we have Solana wallet support in web3 modal, it would be way cleaner and easier for multichain dapps to have it integrated inside web3 modal and using solana/web3.js its not technically complicated

**Comment by CameronButcher** [comment]
Agreed! To have Solana wallets in there as well, would make this so powerful.

In the meantime, I'm gonna go down this route - https://github.com/solana-labs/wallet-adapter
Seems to create a similar effect but for Solana wallets (check out this demo page - https://solana-labs.github.io/wallet-adapter/example/)

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
