### ISSUE TITLE
Web3Modal vanilla js example demo is broken when trying to login with metamask from pc.

### ISSUE THREAD

**Issue by Br3ikros** [WalletConnect/web3modal#459]
Try to go to https://web3modal.github.io/web3modal-vanilla-js-example/ and login from PC using metamask after you just reopened the browser or if it is the first time you connect. It won't let you, giving the following errors:

Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

If you close and reopen the page however (and weirdly enough if the console is open, but not sure if this is just a weird correlation) then the login will work perfectly.

This error seems to occur if you close your browser after logging in, then reopen the browser and try to login again, but only with metamask on PC (so it seems).

May anyone fix this? It's confusing my users a lot

Do this to replicate the error:
go to the demo from pc, login using the metamask option. close your browser. reopen the browser and try to login again from pc using the metamask option. it won't work.

**Comment by Br3ikros** [comment]
anyone?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
