### ISSUE TITLE
web3modal doesn't pop up on Coinbase Dapp Browser

### ISSUE THREAD

**Issue by zerosdontcount** [WalletConnect/web3modal#462]
Hi, 

I've been able to get this to work on basically everything but dapp browsers. Many people who use Coinbase app don't see any modal when a button is connected. Are there any good work arounds to this? I've tried adjusting the CSS to no avail.

**Comment by markusc** [comment]
I was having the same issue just now and downgrading from version 1.9.6 to version 1.9.5 seems to have fixed it.

**Comment by zerosdontcount** [comment]
Thanks mark, that did fix it. Seems the latest update broke this feature.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by eyooooo** [comment]
this is the first hit on google for `web3modal no popup` - if ur having this issue make sure you dont remove the infuraid key from provideroptions or web3modal doesnt fckin work

```
export const providerOptions = {
  walletconnect: {
    package: WalletConnect,
    options: {
      infuraId: "why is this required lmao"  //REQUIRED or no popup
    }
  }
};```
