### ISSUE TITLE
can not set pollingInterval for walletconnect provider.

### ISSUE THREAD

**Issue by foxgem** [WalletConnect/web3modal#488]
in `@walletconnect/web3-provider`, there is a way to set the `pollingInterval`, here is [the code](https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/providers/web3-provider/src/index.ts):
```js
  constructor(opts: IWalletConnectProviderOptions) {
    super({ pollingInterval: opts.pollingInterval || 8000 });
    ...
```

however, the following configuration of WC provider not works in web3modal:
```js
const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
      infuraId: ...,
      pollingInterval: 16000,
    },
  },
};
```

in [this code](https://github.com/Web3Modal/web3modal/blob/master/src/providers/connectors/walletconnect.ts), `pollingInterval` in options is ignored.

**Comment by roto93** [comment]
#294 is a good solution. it extends the original WalletConnectProvider

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
