### ISSUE TITLE
Using injected providers without INFURA_ID?

### ISSUE THREAD

**Issue by Lucienest** [WalletConnect/web3modal#491]
I was wondering why web3modal would require an **INFURA_ID** while many wallets such as Metamask
injects a provider _(i.e: window.ethereum)_ which is being used by many dapps.

```javascript
await window.ethereum.request({method: 'eth_requestAccounts'});
window.web3 = new Web3(window.ethereum);
```

Below [@web3-react/injected-connector](https://www.npmjs.com/package/@web3-react/injected-connector) example
```node
import { InjectedConnector } from '@web3-react/injected-connector'

export const injected = new InjectedConnector({
    supportedChainIds: [1, 3, 4, 5, 42],
});
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
