### ISSUE TITLE
Error: No RPC Url available for chainId: 56

### ISSUE THREAD

**Issue by shaheem-khanzada** [WalletConnect/web3modal#493]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/37620819/171771935-ae63c8fb-0cb1-41cf-a878-8e597d430981.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/37620819/171771991-98b6a3a3-8860-4dc1-903d-1137ab4a20cf.png">

**Comment by evvvritt** [comment]
Having the same issue with 137, despite specifying in rpc options.

**Comment by evvvritt** [comment]
However, @shaheem-khanzada your options uses `rcp` but should be `rcp`. Does it work when you fix that?

**Comment by shaheem-khanzada** [comment]
@evvvritt 
it works now after I did this 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/37620819/171901308-ea4858b0-de44-41ba-a6e9-3e252286adb3.png">

and also remove network key from here 
` web3Modal = new Web3Modal({
        cacheProvider: true,
        providerOptions, // required
    })`

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
