### ISSUE TITLE
web3modal saves provider to local storage but doesn't close modal

### ISSUE THREAD

**Issue by hypekn1ght** [WalletConnect/web3modal#513]
Hi all,

I am having a weird issue where 
`await web3Modal.connect()` would open the modal, clicking the walletconnect section would open the QR code modal.

After assigning the provider to local storage, QR code modal would close and return to the metamask and walletconnect selection modal and stay there.

provider data with key `walletconnect` and value `{"connected":true,"accounts":["0xC7f5fddA7a8c....` is stored in localstorage.

but the promise is not completed. hence the immediate console log after `await web3Modal.connect()` won't get triggered.

Also I can keep clicking the metamask/walletconnect selection modal and local storage value `WEB3_CONNECT_CACHED_PROVIDER` would change to `injected` and `walletconnect` vice versa accordingly. 

Thanks for looking into my issue, hope I can find some help from here! :)

**Comment by Voldemort373** [comment]
I am also facing the same issue. The provider data is stored in local storage, but the promise is not resolved. It would be of great help if someone can help in resolving this...?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
