### ISSUE TITLE
Callbacks not firing on provider but rather on instance

### ISSUE THREAD

**Issue by wengzilla** [WalletConnect/web3modal#520]
I think the documentation might be incorrect... I was trying to follow instructions for listening to callbacks, however, when I used provider, none of the events seem to fire. When I use instance, it works as expected. Is that intended or am I doing something wrong?

The below code _is_ working.

```
const web3Modal = new Web3Modal({
      network: 'rinkeby', // optional
      cacheProvider: false, // optional
      providerOptions: this.getProviderOptions(), // required
    });

    const instance = await web3Modal.connect();
    const provider = new ethers.providers.Web3Provider(instance);

    // Subscribe to accounts change
    instance.on('accountsChanged', (accounts: string[]) => {
      console.log(accounts);
    });

    // Subscribe to chainId change
    instance.on('chainChanged', (chainId: number) => {
      console.log(chainId);
    });

    // Subscribe to provider connection
    instance.on('connect', (info: { chainId: number }) => {
      console.log(info);
    });

    // Subscribe to provider disconnection
    instance.on('disconnect', (error: { code: number; message: string }) => {
      console.log(error);
    });
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
