### ISSUE TITLE
feat(web-components): I'll suggest to migrate to web-components

### ISSUE THREAD

**Issue by mburger81** [WalletConnect/web3modal#540]
Hello,

I'm one of the lead techs of FOOK Token Ecosystem
https://t.me/FOOKTokenOfficial
https://www.fooktoken.com/

Your web3modal is really great and helping a lot all of us dAPP developer, but having the react dependency is in my opinion a big limitation. As I'm also an Ionic/Angular and a StencilJS developer I'll suggest you to migrate your UI components to StencilJS components.
This has many advantages:
  - you remove the React dependency
  - you deliver a plain web3modal web component which you can use in every framework you like
  - with StencilJS you can even deliver native wrapped Angular and React component
  - you have out of the box custom css properties, which makes really easy for custom styling/theming

I think this has many advantages and the afford of doing the migration is very small, because you just need to migrate your few react components.

If you like I can also helping in the migration, but I would like not start if there is not a interest of you to contribute and migrate.

Have a look on the StencilJS documentation
https://stenciljs.com/

**Comment by emirsavran** [comment]
It will be nice for bundle size, see https://github.com/WalletConnect/web3modal/issues/543

I prefer Svelte instead of StencilJS, much smaller bundle size with a few component like web3modal. I can happily help the migration and updating the dependencies of the library.

I saw too many open issues and PRs without any response. Is this repo still active or is it in maintenance mode or something @pedrouid ?

**Comment by mburger81** [comment]
@emirsavran hello may I ask you a question?

is there  a way to "disconnect" from the wallet. Our problem is, once we connect to a wallet and clear the cached provider, once we connect again, Metamask doesn't open to ask us again on which wallet to connect. Web3Modal keeps the last connected wallet which is wired.

Can you help? I ask because in this project there are too many unresponded issues.  thx

**Comment by emirsavran** [comment]
@mburger81 As far as I know, there is no programmatic disconnect in Ethereum wallets. The user needs to disconnect manually.
https://stackoverflow.com/questions/72716168/how-can-i-disconnect-metamask-wallet-using-web3-js

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
