### ISSUE TITLE
Make React peer dependency

### ISSUE THREAD

**Issue by emirsavran** [WalletConnect/web3modal#543]
Hi,

I'm using `web3modal` in a React project. Because `react` and `react-dom` are direct dependencies of `web3modal`, they bundled again with the library.  Total size of the library is 450KB, 114KB comes from `react` dependency. See the below image for details. I suggest use them as peer dependencies like [Solana Wallet Adaptor](https://github.com/solana-labs/wallet-adapter/blob/master/packages/ui/react-ui/package.json). It will greatly reduce the bundle size, 25%.

<img width="1784" alt="Screen Shot 2022-07-30 at 18 36 53 PM" src="https://user-images.githubusercontent.com/4889965/181924471-5c3cccd7-35a9-44c9-b6a2-d999acb83aa1.png">

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
