### ISSUE TITLE
inpage.js:1 Uncaught (in promise) TypeError: Cannot assign to read only property 'selectedAddress' of object '#<l>'

### ISSUE THREAD

**Issue by nrgbistro** [WalletConnect/web3modal#546]
I'm getting this error after adding a provider.on() event. I cannot figure out what is causing it as I've completely disabled and uninstalled web3modal and ethers from my application and I still get the error. Could someone help diagnose what I should do to resolve this?

[Here's a screenshot](https://pasteboard.co/dVgpoHeF4MvE.png) of the issue in the browser console

EDIT: This seems to happen on both changing the chainID as well as the connected account. Please let me know if more information is required to debug this issue.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
