### ISSUE TITLE
Some module has been externalized for browser compatibility. Cannot access it in client code.

### ISSUE THREAD

**Issue by YeungKC** [WalletConnect/web3modal#547]
I hope using web3modal with svelte and follow [Using with Vite](https://github.com/WalletConnect/web3modal#using-with-vite), and I got `Module "http" has been externalized for browser compatibility. Cannot access "http.globalAgent" in client code.`

demo: https://stackblitz.com/edit/vitejs-vite-ogw6et?file=src/App.svelte

**Comment by vdkhvb** [comment]
Fixed it at my end by installing the events and stream modules.
`npm install events`
`npm install stream`

**Comment by LemonNekoGH** [comment]
I am using Vue3+Vite, the same issue.

**Comment by LemonNekoGH** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/issues/341
My be usefull

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
