### ISSUE TITLE
Metamask does not open on opera using web3modal

### ISSUE THREAD

**Issue by UsamaSaleem14** [WalletConnect/web3modal#548]
Hi,

I am using web3modal to connect with different wallets. On Mozilla I am able to connect with metamask but when I open my website on `Opera GX browser (version: LVL4 (core: 89.0.4447.64))` it says that `error: No CLV Wallet found`. Kindly let me know how I can fix this.

Thanks

**Comment by TomSeestern** [comment]
Same here
"Error: No CLV Wallet found" with the version 1.9.8 of web3modal 
Its happening while running: `const instance = await web3Modal.connect();`
Browser: Opera Version: 89.0.4447.83

The current Workaround is a downgrade to the older Version:
"web3modal": "1.9.7",

**Comment by paintoshi** [comment]
I got Opera to work in 1.9.9 by adding this

const isOpera = window.navigator.userAgent.indexOf("OPR") > -1 || window.navigator.userAgent.indexOf("Opera") > -1
let isOperaChromium = false
if(window.chrome !== null && isOpera) {
  isOperaChromium = true
}
const providers = {}

if (isOperaChromium) {
  // eslint-disable-next-line dot-notation
  providers['opera'] = {
    package: true,
  }
} else {
  // add the rest of the providers when using other browsers
  ...
}

However, ended up with two Opera buttons? Both of them work though. But not the Web3, it results in the "no CLV wallet found".

![image](https://user-images.githubusercontent.com/88572775/203000100-38d97e8e-1394-421d-b30d-894c1ab3853a.png)

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
