### ISSUE TITLE
bug: walletconnect provider not working on polygon-mumbai testnet

### ISSUE THREAD

**Issue by akhileshthite** [WalletConnect/web3modal#553]
I'm on localhost:3000 and the walletconnect provider is not working for the infuraId polygon-mumbai testnet (80001 chain), i.e. `https://polygon-mumbai.infura.io/v3/INFURA_PROJECT_ID` URL.
```javascript
walletconnect: {
  package: WalletConnectProvider,
  options: {
    infuraId: { 80001: process.env.REACT_APP_INFURA_MATIC_TESTNET },
  },
},
```

But it's working with the public RPC
```javascript
 rpc: {
    80001: "https://rpc-mumbai.matic.today/",
 }
```

What's the problem here?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
