### ISSUE TITLE
How to catch No RPC available Error

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#561]
Hello, how can I catch this error from a simple web3modal setup? I get it when I connect my trust wallet using walletconnect in a network I haven't provide the RPC. 
I don't want to fix this error, I just want to catch it, the dapp I want to build must have limited Networks. Thank you! <3

`Uncaught (in promise) Error: No RPC Url available for chainId: 2020
    updateRpcUrl index.js:263
    updateState index.js:253
    getWalletConnector index.js:195
    trigger events.js:41
    trigger events.js:35
    _handleSessionResponse index.js:657
    _subscribeToSessionResponse index.js:726
    trigger events.js:41
    trigger events.js:35
    _handleIncomingMessages index.js:710
    _initTransport index.js:806
    _socketReceive index.js:137
    _socketReceive index.js:137
    onmessage index.js:86
    _socketCreate index.js:86
    open index.js:50
    _initTransport index.js:813
    Connector index.js:56
    WalletConnect index.js:5
    WalletConnectProvider index.js:77
    default index.js:45
    o index.js:16
    o index.js:16
    l index.js:16
    l index.js:16
    default index.js:45
    default index.js:45
    connectTo index.js:61
    o index.js:16
    o index.js:16
    l index.js:16
    l index.js:16
    connectTo index.js:61
    onClick index.js:61
    o index.js:37
    N index.js:37
    A index.js:37
    A index.js:37
    ut index.js:37
    rt index.js:37
    ot index.js:37
    Nt index.js:37
    Y index.js:37
    G index.js:37
[index.js:263](webpack://_N_E/node_modules/@walletconnect/web3-provider/dist/esm/index.js?9ef1)
​`

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
