### ISSUE TITLE
WEB3_CONNECT_MODAL_ID div element not displaying above when connecting.

### ISSUE THREAD

**Issue by validateITNikita** [WalletConnect/web3modal#562]
Hello!

Trying to use web3modal with vue 3 ts vite.

And the element not displaying above all elements.
![image](https://user-images.githubusercontent.com/110341248/186764547-7e5c759d-6d08-4ec7-b6b4-5ee5a4f1817d.png)

```
import Web3Modal from "web3modal";
import CoinbaseWalletSDK from '@coinbase/wallet-sdk';
import WalletConnectProvider from "@walletconnect/web3-provider";

const providerOptions = {
  coinbasewallet: {
    package: CoinbaseWalletSDK, 
    options: {
      appName: "CaduceusPunks", 
      rpc: "https://mainnet.block.caduceus.foundation",
      chainId: 256256
    }
  },
  walletconnect: {
    package: WalletConnectProvider, // required
    options: {
      rpc: {
        256256: "https://mainnet.block.caduceus.foundation"
      },
    },
  },
  bitkeep: {
    package: true
  },
  binancechainwallet: {
    package: true
  }
};


async getProviderSignerContract(){
      const web3modal = new Web3Modal({
        network: "mainnet",
        cacheProvider: true,
        providerOptions,
        disableInjectedProvider: false
      });
      const instanse = await web3modal.connect();

      const provider = new ethers.providers.Web3Provider(instanse);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(this.punkAddress, this.punkABI, signer);
    
      return {provider, signer, contract};
    }
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
