### ISSUE TITLE
ethereumjs -abi.git ssh host key error

### ISSUE THREAD

**Issue by marsidorowicz** [WalletConnect/web3modal#565]
Hi, i was using a part with Web3 modal:

```
import Web3 from "web3";
import WalletConnectProvider from "@walletconnect/web3-provider";
import Web3Modal from "web3modal";

// set chain id and rpc mapping in provider options
const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
      rpc: {
        56: 'https://bsc-dataseed1.binance.org'
      },
      chainId: 56
    }
  }
}

const web3Modal = new Web3Modal({
  network: "mainnet", // optional
  cacheProvider: true, // optional
  providerOptions // required
});

const provider = await web3Modal.connect();
await web3Modal.toggleModal();

// regular web3 provider methods
const newWeb3 = new Web3(provider);
const accounts = await newWeb3.eth.getAccounts();

console.log(accounts);
```

to use:
`import WalletConnectProvider from "@walletconnect/web3-provider";`

we need to install:

`npm install --save @walletconnect/web3-provider`

while doing so it requires ethereumjs it on build throws an error:

```
10:59:37 PM: Arguments: ls-remote --tags --heads ssh://git@github.com/ethereumjs/ethereumjs-abi.git
10:59:37 PM: Directory: /opt/build/repo
10:59:37 PM: Output:
10:59:37 PM: Host key verification failed.
10:59:37 PM: fatal: Could not read from remote repository.
```

build is remote with CI on Netlify, without this package all goes ok, seems like an error with this package (not available?)

Cheers, and thanks for help!
Mariusz

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
