### ISSUE TITLE
1.9.8 bitkeep use error

### ISSUE THREAD

**Issue by keepresolve** [WalletConnect/web3modal#574]
![image](https://user-images.githubusercontent.com/29271171/190374424-40e78e32-3a89-4c7b-bd85-53a1c999fd28.png)

Use version 1.9.8

   npm install web3modal@1.9.8

This PR at  https://github.com/WalletConnect/web3modal/pull/569

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
