### ISSUE TITLE
Unable to use Opera & imToken with WalletConnect

### ISSUE THREAD

**Issue by oznekenzo** [WalletConnect/web3modal#60]
Walletconnect is working great via Tokenary & Metamask Mobile, but is not working on Opera Touch & imToken
On both OT & imT, the app is passing `wc:XXXXX.....' into the browser url bar after scanning.

**Comment by julien51** [comment]
I just had that issue.. it would be great if these 2 were supported as well!

**Comment by p0s** [comment]
WalletConnect support in imToken is coming soon! And WC's WalletLink: https://github.com/WalletConnect/walletconnect-monorepo/pull/291

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
