### ISSUE TITLE
Don't mess with parent window scrollbars

### ISSUE THREAD

**Issue by dkent600** [WalletConnect/web3modal#62]
Currently when the modal popup appears, the dApps' scrollbars disappear.  The space gained by hiding the scrollbar(s) causes all the dApp's content to shift around.  This is messy UX.

Would be cleaner if the popup did not mess with parent window scrollbars.

**Comment by miohtama** [comment]
Can you pinpoint a necessary CSS change that could fix this? 

Can you also show an example where this happens? 

Happy to look for a fix.

**Comment by dkent600** [comment]
Thanks @miohtama!

Examples, from https://alchemy.daostack.io/:

Before modal pops up, see scrollbar:

![image](https://user-images.githubusercontent.com/1821666/77907703-126c5700-7258-11ea-9de2-e77432d71359.png)

With modal popped up, no scroll bar:

![image](https://user-images.githubusercontent.com/1821666/77907750-3334ac80-7258-11ea-856a-89227bb4c43f.png)

Everything on the page moves when the scrollbar disappears and reappears.  I guess I would play with the styling of the background that appears under the modal.

**Comment by pedrouid** [comment]
Is this still necessary?

**Comment by dkent600** [comment]
No, is not fixed.

**Comment by pedrouid** [comment]
Alright, I will get it on next release

**Comment by microHoffman** [comment]
@pedrouid @miohtama @dkent600  any news on this? the layout shift is unfortunate:/ thanks for the info

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by Antony-Jia** [comment]
I met same question. Is there any solution?

**Comment by Antony-Jia** [comment]
I met the same question and make body not scroll but root div scoll it can solve
