### ISSUE TITLE
[/React] useBalance not working anymore

### ISSUE THREAD

**Issue by Hidde-Heijnen** [WalletConnect/web3modal#647]
**Describe the bug**
using useBalance to fetch eth or weth balances results in an 429 error from alchemy.

**SDK Version**
    "@web3modal/ethereum": "^2.0.0-alpha.7",
    "@web3modal/react": "^2.0.0-alpha.7",

**To Reproduce**
see:  https://github.com/Hidde-Heijnen/web3modalbug 

**Expected behavior**
fetch balance as before

**Screenshots**
![image](https://user-images.githubusercontent.com/72915404/197284541-6ec0f42c-592b-44ac-917d-cc7c5bb5cba7.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome 
 - Version: 106.0.5249.119 (Official build) (64-bits) (cohort: Stable)

**Additional context**
Check github repo above for reproduction of the problem.

**Comment by IljaDaderko** [comment]
Repo with representation that you provided doesn't seem to include any web3modal related code. At a quick glance, it looks like error is coming from alchemy rpc and `429` indicates "Too many requests".

Perhaps you exceeded your free tier? Are you setting `watch` option to `true` in the hook for live balance updates (it queries rpc every few seconds or uses websocket if available). Maybe you ran this in an infinite loop or something like that?

**Comment by Hidde-Heijnen** [comment]
Omg, im so sorry, I forgot to push to the repo. It has now been pushed. I understand that 429 means to many requests, so I've tried to use a different web3modal project id and a different web3modal account. As far as I know web3modal doesn't have any "tiers" and it uses alchemy under the hood. watch:false doesn't work either. 

Now that the github repo is updated it would be great if you could have another look @IljaDaderko 

> Repo with representation that you provided doesn't seem to include any web3modal related code. At a quick glance, it looks like error is coming from alchemy rpc and `429` indicates "Too many requests".
> 
> Perhaps you exceeded your free tier? Are you setting `watch` option to `true` in the hook for live balance updates (it queries rpc every few seconds or uses websocket if available). Maybe you ran this in an infinite loop or something like that?

**Comment by IljaDaderko** [comment]
@Hidde-Heijnen ty for updating the example 👍 Any chance you could give me any usage / volume estimates of how many rpc calls you are making and how often? Are you using this rpc heavily or its normal use?

If you inspect your network, are requests being made to https://rpc.walletconnect.com (similarly to how they are on example app https://web3modal.pages.dev)? I'm trying to figure out where that alchemy url is coming from, is it only returned as part of the error or are you using alchemy as your provider instead of walletconnect?

**Comment by IljaDaderko** [comment]
Ok, I see what the issue is, you have not provided some config options i.e. your example ethereum config does not have `chains` or `providers`. Therefore you are using default options, one of which is normal `publicRpc`, that is highly rate-limited and is alchemy one (not wallet connect)

If you want to use walletconnect rpc (or add your api key to alchemy) you need to specify that in config object. Here is an example of how to do it in order to use walletconnect rpc

https://github.com/WalletConnect/web3modal/blob/V2/examples/react/src/pages/_app.tsx#L27

And here is documentation for all possible config options

https://github.com/WalletConnect/web3modal/tree/V2/chains/ethereum#configuration

This should solve your issue, but if you need more help feel free to ping me here again 👌

**Comment by Hidde-Heijnen** [comment]
I will be using my own rpc url from now then, since we are also running our own node, but I still find it strange that this was working perfectly a few days ago. 

Final question: why does useBalance fetch so many times? Does it automatically refetch? you can see in the console how many times it is loggin undefined first and then the error, I don't see why that is necessary. 

PS: documentation for react is not really fully complete,  and most examples show /ethereum import instead of /react, but glad that you guys are working on it!

**Comment by Hidde-Heijnen** [comment]
It seems to work with the walletconnect rpc, is there also a rate limit for that?

**Comment by IljaDaderko** [comment]
> why does useBalance fetch so many times?
`useBalance` Should make 1 rpc call, but it will re-render multiple times as it goes through.

1. Initial state (undefined)
2. Loading state
3. Data available / error state

There are also extra options that can affect this i.e. if you set `enabled: false` it will not fetch when hook is rendered, default is true. If you set `watch: true` it will use polling or websocket (if available) to refresh balance. With polling it will make a request every few seconds. Default here is false.

With walletconnect rpc there is generous allowance, so you shouldn't come across any issues with normal use. We will document more concrete numbers very soon.

> but I still find it strange that this was working perfectly a few days ago
All depends on how alchemy rate limits here

**Comment by Hidde-Heijnen** [comment]
That's all, have a nice day, and thanks for the help! Why not use the walletconnect rpc URL as default though, since you already have to put in your walletconnect projectID?

**Comment by IljaDaderko** [comment]
> Why not use the walletconnect rpc URL as default though, since you already have to put in your walletconnect projectID?

This will be the case once we move into beta or prod releases of web3modal 👌
