### ISSUE TITLE
Remote localhost development does not work without https on iOS

### ISSUE THREAD

**Issue by fibo** [WalletConnect/web3modal#664]
**Describe the bug**
When developing locally using my iPhone, I cannot connect to Metamask

sorry I do not have time right now to document everythink, I am hacking at ETH Lisbon.

 You can find instructions about how to run the webapp here https://github.com/fibo/pom-eth-lisbon/tree/main/frontend#readme

use command `npm run dev` then connect with an iPhone Safari.

![IMG_0378](https://user-images.githubusercontent.com/176730/198868033-067d15ae-43ae-4076-b74a-5f4a0ba214eb.PNG)

**SDK Version**
 - Version [e.g. v1.9.8 or 2.0.0-alpha.2]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IljaDaderko** [comment]
@fibo https://github.com/fibo/pom-eth-lisbon 404s for me, is it private?

**Comment by fibo** [comment]
@IljaDaderko now it is public

I also explained the issue to your collegue here at ETH Lisbon. He said that it could be Swift related or something like that (sorry I did not sleep, hacked all the night)

It is easier to reproduce it with this fresh repo https://github.com/fibo/hello-walletconnect

just removing `HTTPS=true` in npm start script.

**Comment by IljaDaderko** [comment]
@fibo ty for the repro. I think debugging and fixing this might take a while (sorry for the blocking issue on your hackathon project). I'm relatively confident that it might be something related to webpack and how it loads dev scripts up on localhost in iPhone. My best suggestion for hackathon would be something like this:

Can you try this in a non create-react-app environment i.e. maybe use vite with its react plugin, they have example of this here https://stackblitz.com/edit/vitejs-vite-u2dikj

I believe this could be a quick change as both are relatively similar in setup. Since vite is not using webpack under the hood, this might work on localhost / iPhone.

**Comment by 0xAsimetriq** [comment]
After digging deeper into this, https error seems to be related to web tools, I was able to work on this remotely in nextjs example. Also works on simulator when you access your localhost via 10.0.1.1
