### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#672]
From @errorists:

I’m most curious about having a global shortcut to open the modal. I would love having that, just mash on keyboard to connect to any web3 app, no need to hunt for the button

Research keyboard navigation. → ← ↑ ↓ Arrows to select wallets/networks on the grid, Enter to confirm, Backspace to go back, Escape to close, cmd+k to go straight to Search. cmd+o to open the modal

correct highlighting of selected wallets is dependant on
For items on grids (wallets / networks) use a light overlay background for hover.

**Comment by ef3n9r98** [comment]
Hi @hatskier, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ]([www.openq.dev](http://www.openq.dev/)).

Thanks!

**Comment by ef3n9r98** [comment]
Hi @0xAsimetriq and @chadyj, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ]([www.openq.dev](http://www.openq.dev/)).

Thanks!

**Comment by glitch-txs** [comment]
Some concerns on this:
1. Some dapps might have other features/products that use shortcuts and they could conflict with Web3Modal ones.
2. Due to 1 there might be no consistency across different dapps and that'd make it "fradgile", e.g. a user using a key that does something different to what he/she thought.

**Comment by enesozturk** [comment]
@glitch-txs, do you have some dApp examples that have shortcuts enabled? 

I'd like to see if it really could cause such problems. We could think it about like [cmdk](https://github.com/pacocoursey/cmdk). If we'd only listen key events when then modal is open, and if we put simple keys (rather than key combinations like ⌘ + K, etc.), it should handle our basic needs to redirect in the modal. 

I think we could even allow users to override key combinations for such event like the following etc.

```js
createWeb3Modal({
  shortcuts: {
     openModal: ["⌘", "K"],
     networks: ["N"]
  }
})
```

There could be shortcut indicators as the following that can be toggeled on/off; 

<img width="300" alt="Screenshot 2024-01-06 at 20 49 51" src="https://github.com/WalletConnect/web3modal/assets/19428358/6149ddc2-6045-4913-89f9-0989bf972817">


Also as I remember from the hack-week designs, we'll be refactoring the account (home) page and have settings on another page, so this could be configured inside that page or something like that

**Comment by glitch-txs** [comment]
I don't think this is necessary (we don't have requests afaik), also for some buttons like "buy" it might be okay to make them hard to action, e.g. wallets don't allow you to use enter to accept a tx request, for security reasons. In the case of email we'd need to turn this off if the input is focused, if it's not and the user is not aware it might activate unwanted buttons.

**Comment by Jeremy293** [comment]
https://github.com/reown-com/appkit/issues/672
