### ISSUE TITLE
Support standard js bundles from cdn

### ISSUE THREAD

**Issue by meatballs** [WalletConnect/web3modal#678]
**Describe the bug**
When attempting to use Web3Modal from skypack, I get:
```
Uncaught TypeError: Cannot read properties of null (reading 'Logger')"
```

**SDK Version**
 - Version  2.0.0-alpha.2

**To Reproduce**
https://jsfiddle.net/L2f0bqcw/

which simply attempts to the import the modules using:
```js
import { ClientCtrl, ConfigCtrl } from 'https://cdn.skypack.dev/@web3modal/core'
import { chains, providers } from 'https://cdn.skypack.dev/@web3modal/ethereum'
```

**Comment by IljaDaderko** [comment]
Hey @meatballs, ty for the report. Not familiar with skypack, is there any special configuration we need to add in order to support it?

All packages export es module with entry under `dist/index.js`, we also specify this info in package.json via https://github.com/WalletConnect/web3modal/blob/V2/packages/react/package.json#L4-L9

**Comment by meatballs** [comment]
I don't believe there's any special config necessary - they just build whatever they find on npm.

They do have a checking tool which might flag something: https://docs.skypack.dev/package-authors/package-checks

**Comment by meatballs** [comment]
It looks like it's something in the ethers library. Looking in the browser console on that jsfiddle, I can see:
```
ethers.js:95 Uncaught TypeError: Cannot read properties of null (reading 'Logger')
    at ethers.js:95:30
    at createCommonjsModule (ethers.js:17:10)
    at ethers.js:19:22
```

L95 is:
```js
  var logger2 = new logger_1.Logger(_version_1.version);
  exports.logger = logger2;
});
```
