### ISSUE TITLE
Adding the Opera wallet provider results in duplicate buttons

### ISSUE THREAD

**Issue by paintoshi** [WalletConnect/web3modal#715]
Was looking into this problem: https://github.com/WalletConnect/web3modal/issues/548
But didn't want to downgrade. Added the opera provider instead (when detecting Opera browser):

```
{
  opera: {
    package: true
  }
}
```

**SDK Version**
 - Version [v1.9.9]

It works as expected, but seeing two Opera buttons on the modal? If removing the above code from the providerOptions, that's being passed to the "new Web3Modal", there are no Opera buttons. The Web3 button can be removed by using "disableInjectedProvider: true".

![image](https://user-images.githubusercontent.com/88572775/203003045-fcf1d029-5b37-4663-b176-72479fe955b4.png)

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
