### ISSUE TITLE
grant OAuth access to GitKraken to access your repo

### ISSUE THREAD

**Issue by dkent600** [WalletConnect/web3modal#73]
Would it be possible for you to grant OAUTH access to GitKraken to access your GitHub repository?   Thanks!

https://www.gitkraken.com/

![image](https://user-images.githubusercontent.com/1821666/63872176-5bd78980-c98b-11e9-8cd2-708b92274f2d.png)

**Comment by pedrouid** [comment]
Is this still necessary?

**Comment by dkent600** [comment]
Sorry, I'm afraid don't know.  I think you can tell by looking in github Settings=>Applications=>Authorized OAuth Apps where you should see GitKraken listed.

**Comment by pedrouid** [comment]
Do you still need to maintain this fork after we added to caching and improved provider controls?

**Comment by dkent600** [comment]
I'm done with the fork for now, thanks.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
