### ISSUE TITLE
WalletConnect BSC Error - PollingBlockTracker using Custom Rpc | WEB3MODAL

### ISSUE THREAD

**Issue by pietrociatta** [WalletConnect/web3modal#739]
**Describe the bug**
I've set-up the v1 of the web3modal following the repo and some github issue, to use walletconnect/we3-provider.
In the options i've setup a custom rpc (quicknode) for the Binance smart chain, it connects correctly to the wallet but when i connect an error appears.

<img width="986" alt="Screenshot 2022-11-28 alle 08 30 59" src="https://user-images.githubusercontent.com/59965830/204219080-28d24837-d88b-48f8-b34f-24998fa4f328.png">

After this error if i open up the console i see this error looped:
<img width="650" alt="Screenshot 2022-11-28 alle 08 31 37" src="https://user-images.githubusercontent.com/59965830/204219237-46c1d557-c2cd-4fdf-b743-261ff0049944.png">

Below you can check my code (i replaced the quicknode rpc with binance to not showing the endpoint, but also with this bsc dataseed rpc it's not working, same error as the quicknode rpc):

 const providerOptions = {
      walletconnect: {
        package: WalletConnectProvider,
        options: {
          rpc: {
            56: 'https://bsc-dataseed.binance.org/',
          },
          network: 'binance',
          chainId: 56,
        },
      },
    };

    const web3ModalInstance = new Web3Modal({
      disableInjectedProvider: false,
      network: 'mainnet',
      theme: 'dark', // optional
      cacheProvider: true, // optional
      providerOptions, // required
    });

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
