### ISSUE TITLE
Error when using in an angular 15 application

### ISSUE THREAD

**Issue by bjbraz** [WalletConnect/web3modal#743]
**Describe the bug**
When im trying to use web3modal in an angular 15 application, im receiving this error in ```ng build``` and ```ng serve```

**SDK Version**
    "@walletconnect/web3-provider": "^1.8.0",
    "rxjs": "~7.5.0",
    "web3": "^1.8.1",
    "web3modal": "^1.9.10",

**To Reproduce**
When im running ```ng build``` im receiving this error: 
```
Error: node_modules/web3modal/dist/providers/connectors/ledger.d.ts:1:43 - error TS2307: Cannot find module 'src/helpers' or its corresponding type declarations.

1 import { IAbstractConnectorOptions } from "src/helpers";
                                            ~~~~~~~~~~~~~
```

**Expected behavior**
ng build and ng serve working fine, without errors

**Screenshots**
![Screenshot 2022-12-01 at 15 11 38](https://user-images.githubusercontent.com/117951905/205128796-0bb279a8-2242-47f2-a215-270fb410f0b9.png)

**Desktop (please complete the following information):**
 - OS: mcOs ventura 13.0.1
 - Browser Google Chrome
 - VersionVersion 107.0.5304.110 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by p0st1t** [comment]
Same here

**Comment by armyofda12mnkeys** [comment]
Would love an angular tutorial on how to integrate a wallet like this to use MetaMask so that all routed child components will get it. using Angular 14.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by REPTILEHAUS** [comment]
using version 1.9.9 works but when will actual angular support be introduced ? I have to create so many hacks just to get something up and running, surely there is some kinda easy way to create a framework agnostic abstraction so any javascript framework can use this
