### ISSUE TITLE
Modal isn't properly visible using Brave Browser

### ISSUE THREAD

**Issue by billyjacoby** [WalletConnect/web3modal#772]
**Describe the bug**
When using Brave Browser the WalletConnect modal either doesn't popup or is barely visible.

**SDK Version**
 - Version current - 1.9.8

**To Reproduce**
Issue can be viewed by visiting the provided example applications on Brave Browser:
https://react-app.walletconnect.com/

And clicking the connect button. The modal will either not popup or only the top will be visible on the bottom of the screen.

**Expected behavior**
WalletConnect works as expected in Brave Browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0xAsimetriq** [comment]
This is what I see when using brave and macOS. I assume this issue is related to screensize perhaps? Could you drop a screenshot and details of your screen i.e dimensions / are you zoomed in etc.

<img width="1512" alt="Screenshot 2022-12-15 at 10 29 27" src="https://user-images.githubusercontent.com/3154053/207810473-141c5ed3-6848-47ce-86ee-329e31ca8e9e.png">

**Comment by 0xAsimetriq** [comment]
Closing this since it has been a while from last response and we are now few versions ahead. Modal's open method can now be `awaited` which makes things more stable (we ensure that everything is ready even on slower networks).
