### ISSUE TITLE
Not seeing full desktop wallet options

### ISSUE THREAD

**Issue by WyattMufson** [WalletConnect/web3modal#775]
**Describe the bug**
When the modal is opened it first only shows me the mobile QR. If I click the "?" icon and go back then it shows me the ability to click the desktop wallets. When I view all of the desktop wallets not all of them are available (such as Coinbase wallet). How can I customize the UI to always show desktop wallets and include the full list

**SDK Version**
 - "@web3modal/standalone": "^2.0.0-beta.9"
 - "@walletconnect/universal-provider": "^2.1.4"

**To Reproduce**
1. Initializing a UniversalProvider
2. Calling connect
3. Initializing an instance of Web3Modal
4. Calling `openModal` with the uri on the `display_uri` event (screenshot 1)
5. Click "?" button 
6. Click view all options (screenshot 2)

**Expected behavior**
UI should always show desktop wallets and include the full list

**Screenshots**
<img width="351" alt="Screen Shot 2022-12-15 at 4 45 40 PM" src="https://user-images.githubusercontent.com/10342911/207974354-502e3914-0304-4263-8afd-837f01375487.png">
<img width="350" alt="Screen Shot 2022-12-15 at 4 46 01 PM" src="https://user-images.githubusercontent.com/10342911/207974368-3edd4049-1731-4756-838c-9d982643238f.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by 0xAsimetriq** [comment]
Do you have a repo with your implementation to reproduce this issue by any chance? Desktop wallets not being shown there initially sounds like a legitimate bug.

In terms of wallets like mm, coinbase etc. not showing up, that is by design in `@web3modal/standalone` package. Reason they are not there is that standalone is intended to be used where:

1. Someone already manages wallets like metamask / cb in their custom ui and only needs WalletConnect
2. Someone is not using wagmi (these wallets are wagmi connectors)
3. Someone is using w3m on a non evm chain

If you don't fall under one of those, you likely want to use `@web3modal/html` package alongside `@wagmi/core` which will have all those wallets.

**Comment by WyattMufson** [comment]
Thanks for the quick reply — I don't have a public repo I can share. I've also noticed that removing the projectId when initializing the web3modal/standalone makes it so that the desktop wallets never appear.

In terms of standalone vs html:
1. There is no injected wallet integration.
2. I'm not using wagmi
3. Right now it's just evm, but like that the universalprovider is already setup to handle other chains

I like the simplicity and how straightforward it is to make a connection via the [walletconnect/universal-provider](https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/providers/universal-provider) and for the web3modal/standalone to only require calling open and close. This way I can call the code in any arbitrary spot in my codebase without the need to modify the html or React code. 

I'm not looking to integrate any injected wallets, I just want to allow users to scan a QR code or signin via one of the desktop integrations — so for coinbase would be the wallet link QR and MetaMask would just be once they update to WCv2. 

So my questions are:
- Is that something that is possible? 
- Is there a way to pass in custom connectors to the standalone version? 
- Is the intended use for the universal-provider for just with wallet connect and not Coinbase?

Here's a basic version of the code (assume variables are defined):

```
import UniversalProvider from '@walletconnect/universal-provider';
import { Web3Modal } from '@web3modal/standalone';

const provider = await UniversalProvider.init({ projectId, metadata });
const web3Modal = new Web3Modal({ projectId, standaloneChains });
provider.on('display_uri', (uri: string) => {
  web3Modal.openModal({ uri });
});
await provider.connect({ namespaces });
web3Modal.closeModal();
```

**Comment by glitch-txs** [comment]
hey @WyattMufson could you make it work? I have the same issue although it could be handled by using the window.ethereum provider.

My current issue @0xAsimetriq the QR Code on desktop is not working for metamask when I try to scan with my phone, I can the QR with metamask mobile app and nothing happens. I'm using the standalone modal as well, I even tried it on the example provided in the web3modal repo, the react-standalone example.

**Comment by 0xAsimetriq** [comment]
@glitch-txs You probably followed v2 documentation, which metamask currently doesn't support (they are working on it though).

Here is v1 https://docs.walletconnect.com/1.0/quick-start/dapps/client just replace `qrcode-modal` package with new web3modal.

**Comment by WyattMufson** [comment]
@0xAsimetriq would love a response to my questions. What's the reason this was marked as closed? My issue has not been resolved yet

**Comment by 0xAsimetriq** [comment]
@WyattMufson Mainly due to not being able to reproduce issue without a more in depth example. But having info that you provided above I could point to these ideas

1. If no `projectId` is provided, then we cant query our explorer api at https://explorer.walletconnect.com hence there is no wallet data
2. Depending on which `standaloneChains` chainId's were provided, it could be the case that there are no wallets supporting that chain(s), thus nothing is shown
3. Wallets like `MetaMask` / `Coinbase` etc. that come from wagmi connectors will not be shown in standalone mode (as they need wagmi and our managed flows)
4. It is possible to define manual wallet configs via [config](https://docs.walletconnect.com/2.0/web3modal/configuration) options like `mobileWallets`, `desktopWallets` and add their associated media with `walletImages`
