### ISSUE TITLE
something might be wrong with "copy qrcode flow" WalletConnect V1 - Sometime cannot connect when using Wallet and Dapp in same mobile device

### ISSUE THREAD

**Issue by HieuNguyenD** [WalletConnect/web3modal#778]
Hi, i just wonder if anyone occur the same issue , or if someone can help/suggest the solution to fix ...

Sometime cannot connect when using Wallet and Dapp in same mobile device

I have tried using some wallets (for example: BitKeep and TrustWallet...)which has function to use QR photo or paste QR from clipboard to use walletconnect

Just want to clear that it works perfectly if the wallet and dapp is open on seperate devices AND
this issue happens sometime ( not 100% )

Step to reproduce ( same mobile device ):
1 open browser, Copy ( or capture ) QR of Walletconnect from any DAPP 
2 open Wallet app => connect dapp using above Screenshoot or paste text from clipboard
3 Confirm the connection on wallet => wallet show connect successfully
4 Open browser tab on step 1: => notice that Dapp doesn't response ...

https://user-images.githubusercontent.com/32504180/208394977-f6ad5181-006c-4c00-946a-2f213ba8a872.mp4

Anyone suggestion or advice will help... i'm really appreciate

**Comment by Usernamethoma** [comment]
@HieuNguyenD We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
