### ISSUE TITLE
When I customize my wallet, there are two metaMasks, and my customized metaMask wallet cannot be linked, and there is also an additional coinbase wallet.

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [WalletConnect/web3modal#808]
**Describe the bug**
When I customize my wallet, there are two metaMasks, and my customized metaMask wallet cannot be linked, and there is also an additional coinbase wallet.

**SDK Version**
 - Version [2.0.0-rc.1]

**To Reproduce**
https://codesandbox.io/p/sandbox/strange-sinoussi-it3utr?file=%2Fsrc%2Fcore%2Findex.ts&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A110%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A110%7D%5D

**Screenshots**
<img width="538" alt="image" src="https://user-images.githubusercontent.com/17617821/210297606-0669f8cc-371a-45cb-88dd-bf1b342f72e8.png">

**Comment by 0xAsimetriq** [comment]
@shenhaoguangDayDayUp 

1. You see first metamask and coinbase wallets, because these are configured in wagmi when you use our `modalConnectors()` preset. To  remove them you need to change it to something like this (only wallet connect connector is required):

```
connectors: [new WalletConnectConnector({ chains, options: { qrcode: false } })]
```

2. Specifying metamask like that in `desktopWallets` will not work. This configuration is only for native desktop wallets that can be deep linked into, which metamask is not, it is a browser extension also known as `injected wallet`. You need to use wagmi's `InjectedConnector` for that. Due to the nature of ethereum, if you have multiple extensions, they will conflict with one another. In web3modal we use this `InjectedConnector` in our defaults and show you either first installed extension that was loaded in or fall back to metamask (which will ask user to install it).
