### ISSUE TITLE
Hello You have a function switch account metamask

### ISSUE THREAD

**Issue by champseo2017** [WalletConnect/web3modal#835]
Hello You have a function hook that holds clear eth_accounts or wallet_requestPermissions .

example 

```
const provider = await web3Modal.connect();

   const result = await provider.request({
     method: "wallet_requestPermissions",
     params: [
       {
         eth_accounts: {}
       }
     ]
   });
```

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by champseo2017** [comment]
@0xAsimetriq  Thank you so much means Auth functions are like switch account ? in ver.2.0

**Comment by 0xAsimetriq** [comment]
V2 Modal integrates really well with https://wagmi.sh you can either grab raw provider from there that will have these or use their actions (vanilla) / hooks (react) for various operations like this.

**Comment by champseo2017** [comment]
Thank you very much for the answer.
