### ISSUE TITLE
Conflicts between extensions when multiple are installed on window.ethereum

### ISSUE THREAD

**Issue by kombos** [WalletConnect/web3modal#892]
**Describe the bug**
on installing both metamask and trust wallet extensions, the metamask entry dissappears from featured list. on selecting metamask from 'view all', it goes to 'install metamask' page. 

**web3modal Version**
 - Version : 2.1.1

**To Reproduce**
1. install trust and metamask
2. open web3modal
3. metamask option now says 'install wallet' and it not in the featured list

**Expected behavior**
1. metamask should still be in featured list, alongwith trust wallet in featured list or part of 'view all'.

**Comment by 0xAsimetriq** [comment]
We've got something in the works to improve ux around this, but as most extensions override `window.ethereum` some issues will likely still persist. This is a common problem in this space in general. EIP exists to try and improve this https://eips.ethereum.org/EIPS/eip-5749

Will update this issue once we roll out ux improvements mentioned above

**Comment by daenamkim** [comment]
FYI, the same thing happens as well on both MetaMask and Coinbase wallet extensions were installed.

<img width="647" alt="Screenshot 2023-02-22 at 14 51 38" src="https://user-images.githubusercontent.com/16159767/220535218-d26ab6e1-c87d-4b88-b3b2-040ec7543a1b.png">

**Comment by daenamkim** [comment]
FYI, hopefully https://eips.ethereum.org/EIPS/eip-5749 might be helpful in the near future.

**Comment by 0xAsimetriq** [comment]
Both of these add `window.ethereum.isMetaMask` flag, thus we have to first check for the "other" extension and then fall back to meta mask (otherwise we would be ignoring a big chunk of extensions since most of these do this).

As I mentioned above, we solve some of these issues by managing extension entries in our cloud dashboard (have more data), so can deduplicate these better. This will be implemented soon.

**Comment by ArcQ** [comment]
is there an eta for the ux changes?

in the meantime is there any way to work around metamask not being detected at all? 
or a way to always feature metamask + detect that the extension is there?

it's just a very big pain as we have quite a few users who have both coinbase wallet + metamask installed

**Comment by 0xAsimetriq** [comment]
@ArcQ Some of these will go out in next release, but in general issue will still remain at large, it's just nature of `window.ethereum`.

Wallet connect started pushing for adaptation of `eip-5749`, we are chatting with a lot of wallets, will be hosting twitter spaces next week discussing this publicly, but ultimately issue will be solved only once majority + top wallets like metaMask agree and adopt the changes.

Extensions like coinbase delay their initialization so they can add themselves onto `window.ethereum` after metamask, essentially rendering it unusable.

MetaMask is particularly big issue due to it's dominance i.e. almost every extension either removes it or tries to act / mask as it in order to be more compatible with dapps.

**Comment by UTkzhang** [comment]
Could you take a look here when you get a chance? I am a bit puzzled by the force override of metamask wallet specifically to use the injected window.ethereum provider, so we can't even override it in the wagmi client: https://github.com/WalletConnect/web3modal/pull/967

**Comment by 0xAsimetriq** [comment]
@UTkzhang This is what's included in `w3mConnectors` https://github.com/WalletConnect/web3modal/blob/V2/chains/ethereum/src/utils.ts#L35

As you'll notice there is `InjectedConnector`, a wagmi connector used for all injected wallets. `MetamaskConnector` is essentially the same as this one, but it will only check for metamask. If you add 2 of these together, they'll likely act the same when metamask is installed. If there are 2 extensions I think injected connector will use whichever loaded itself onto `window.ethereum` last while metamask will not work at all or will behave same as the other (it depends if other extension also sets window.ethereum.isMetaMask flag)

If you still want to use MetamaskConnector, just remove `w3mConnectors` and use WalletConnectConnector (or legacy one) + Metamask one 👍

**Comment by chenkuangkuang** [comment]
@0xAsimetriq  Is there a more specific example of how WalletConnectConnector and Metamask work together? Where to export Metamask?

**Comment by 0xAsimetriq** [comment]
Comment above is probably as specific as it gets. Metamask is managed via InjectedConnector

**Comment by 0xAsimetriq** [comment]
PR looks good, and will be part of 2.3.0, but realised likely in a different format due to bigger refactor around injeted wallets. However using metamask connector will likely not solve the issue, as it will open another connector. It's just the nature of how `window.ethereum` functions at the moment.

**Comment by UTkzhang** [comment]
it solves it if you just need metamask to show always, regardless of the window.ethereum injected wallet(s). All we have to do is do a quick uniqueness check on the w3mConnectors and metamask connector, and if theres a duplicate remove the latter override.

**Comment by UTkzhang** [comment]
but thanks appreciate the quick response

**Comment by bfriel** [comment]
Hi @0xAsimetriq , do you have guidance for how other injected wallets can co-exist alongside Metamask in future releases of Web3Modal? 

For background, we at Phantom also inject our provider at `window.phantom.ethereum`. We have worked with a few teams to detect that provider to show Phantom buttons alongside MetaMask buttons. In turn, we can turn off our `window.ethereum` injection on these sites so that users can use either wallet interchangeably without collisions. We'd love to work with you on a similar solution.

**Comment by 0xAsimetriq** [comment]
It's tricky. We use wagmi (and in future will have lighter versions of modal relying on viem) library which does not cater to individual cases like this. Honestly I also think it is not a good idea to do this and instead we (as a community) should focus on pushing new standards like https://eips.ethereum.org/EIPS/eip-5749 forward.

WalletConnect is already on this with others, hoping to have this (or its upgraded version) as a standard soon. I'm sure wagmi guys as well as us will be able to implement this fast.
