### ISSUE TITLE
[bug]  - UI connect button not shown

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#917]
### Link to minimal reproducible example

-

### Summary

Issue on Iphone 14 Pro max, safari.

I've tested the same website on Android Xiaomi and works fine.

![Image from iOS](https://user-images.githubusercontent.com/66949816/222514684-daba390b-70a9-4424-b5bc-4349fbfd281d.jpg)

### List of related npm package versions

```json
    "@walletconnect/sign-client": "^2.4.6",
    "@walletconnect/universal-provider": "^2.4.6",
    "@web3modal/standalone": "^2.1.2",
```

**Comment by 0xAsimetriq** [comment]
Needs link to minimal reproduction, could be the case where no compatible wallets exist for defined chains / options.

**Comment by glitch-txs** [comment]
Thanks, I've updated the link. We tested it on Trust Wallet browser and on Safari browser in said mobile phone, it worked on an Android. Might it be Trust Wallet ios support issue?

**Comment by 0xAsimetriq** [comment]
Hey @glitch-txs ty for the updated link 👍 I'm confused to what you expect to happen on iOS? I can see that you are using standalone modal and commenting out projectId. If projectId is not provided, there is no way for us to fetch data from https://explorer.walletconnect.com to get a list of wallets which is required for ios, if you want to show them.

Android is different to iOS as we can open `wc://` deeplink and it will show you all available apps (wallets) that can handle this deeplink. This is not the case iOS, because native os does not support it.

Perhaps this difference in iOS and Android is where confusion comes from?

**Comment by 0xAsimetriq** [comment]
@glitch-txs yes `explorerAllowList:[]` is similar to not providing projectId in this case, as no wallets are allowed to be fetched from our explorer api.

**Comment by glitch-txs** [comment]
Thanks @0xAsimetriq !, it seems trust wallet key and others are not working. Here you can see it only shows one wallet
![doesntwork](https://user-images.githubusercontent.com/66949816/222894410-238a6264-0a56-45e0-8cfd-85d938b7897a.jpeg)

you can check in my last commit, I ended up removing `explorerAllowList:["keys"]` and now it looks like this:

commit:
https://github.com/glitch-txs/metamask-walletconnect-ethers-zustand/commit/b9b93f8da0e6b392d413e3d3b0887a9dc755128d

![doesntwork](https://user-images.githubusercontent.com/66949816/222894459-fb837602-3d6b-449a-a37b-36390a67eb29.jpeg)

You can also see the keys I was using in the same commit. Thanks again!
