### ISSUE TITLE
[bug] iOS not showing Metamask Icon while Android yes

### ISSUE THREAD

**Issue by Trynight** [WalletConnect/web3modal#938]
### Link to minimal reproducible example

https://deelance.com/

### Summary

Hello, as title, on iOS the Metamask Icon is not showing as option to connect, while on Android and Desktop is fine.

### List of related npm package versions

"@web3modal/ethereum": "2.1.2",
"@web3modal/react": "2.1.2",
"wagmi": "^0.11.7",

**Comment by 0xAsimetriq** [comment]
This is due to using version `2`, MetaMask does not support it yet (they are working on it however).

Android has a special view where wallet animation is shown, but wallets are opened in a native modal that appears showing you all installed apps that can handle `wc://...` deeplink, hence why it's shown there. We'll need to work on androids view to make it more clear.
