### ISSUE TITLE
2.3.0 - Pick your wallets, new ui, multiplatform wallet support and more!

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#981]
### Changelog
https://github.com/WalletConnect/web3modal/releases/tag/2.3.0

**Comment by UTkzhang** [comment]
We just tried 2.3.0 and still face multiple extensions issues. To reproduce, use any included example and have chrome coinbase wallet and metamask. Even though the wagmi injected connector is coinbase in this case, the icon on w3mmodal is metamask. When clicked, it opens coinbase wallet. This is arguably worse behaviour than 2.2.0? I think we should always show the correct wallet rather than overriding injectedconnector wallet with something else, unless something is incorrect with our testing. If we get the 2.2.0 behaviour where coinbase is shown and metamask is not detected, but instead just remove the forced override of id metamask check as per https://github.com/WalletConnect/web3modal/pull/967, then we can always force metamask to be present regardless of injected connector.

**Comment by UTkzhang** [comment]
it seems like it is back to the v2.2.2 solved issue of icon/name and connector mismatch

**Comment by 0xAsimetriq** [comment]
If you look into `window.ethereum` you'll see that coinbase masks as metamask when both are installed. Disable mm and you should see coinbase icon / name. There is no reliable way to opperate multiple injected wallets, hence addition of that footer notice. As of now following EIP https://eips.ethereum.org/EIPS/eip-5749 is being considered (will likely be updated though). Once injected wallets implement something like this, we'll be able to have multiple of them supported at the same time.

I'll look into retry bit not woking, it should become enabled once extension reports an error (i.e. canceling request or closing the window). Could be the case where coinbase doesn't report such error when it is in that locked state?

**Comment by 0xAlexander** [comment]
When introducing 

`ExplorerRecommendedWalletIds`

A weird miss-match happens between PC & Mobile (Android & iOS)

- On PC, the introduction of the command works as expected; recommends the chosen wallets & in "View All" the rest of the available wallets exist.
- On Mobile (iOS), the "View All" folder with the rest of the wallets **doesn't appear at all.**
- On Mobile (Android), a whole different slider comes up, with the recommended wallets, and then blank icons rolling around in a carousel fashion

Same code, but different devices. You can check screenshots for visual aid. What's the correct or expected behavior here?

Code Snippet:
```
explorerRecommendedWalletIds={[
           'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96', // MetaMask
           '1ae92b26df02f0abca6304df07debccd18262fdf5fe82daa81593582dac9a369', // Rainbow Wallet
           '4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0', // Trust Wallet
        ]}
```
![](https://cdn.discordapp.com/attachments/1097843008201818192/1097843008810000464/image.png)
![](https://cdn.discordapp.com/attachments/1097843008201818192/1097845964909322301/IMG_3886.JPG)
![](https://cdn.discordapp.com/attachments/1097843008201818192/1097843008478662788/IMG_3885.jpg)

**Comment by 0xAsimetriq** [comment]
@0xAlexander Replicated, will fix in next release 👍 android view will be still unique due to different deeplink handling there, but I'll re-use existing images so it doesn't look out of place like that.

**Comment by 0xAlexander** [comment]
> @0xAlexander Replicated, will fix in next release 👍 android view will be still unique due to different deeplink handling there, but I'll re-use existing images so it doesn't look out of place like that.

Is 2.3.1 supposed to fix the whole issue? The thing that was fixed seems to be the carousel of images for Android. That's one part.

The folder "View All", containing all the other supported wallets, is still missing while `ExplorerRecommendedWalletIds` is used int the code. `ExplorerRecommendedWalletIds` seems to be blacklisting all wallets not mentioned in the recommended list, which is not sustainable.

In my opinion it should just push a select few in front and behave as PC behaves on all other devices.

**Comment by 0xAsimetriq** [comment]
@0xAlexander does `2.3.2` solve that remaining issue?

**Comment by 0xAlexander** [comment]
> @0xAlexander does `2.3.2` solve that remaining issue?

1) iOS "View All" now works, even if 1 or 2 recommended wallets have been selected. **So that is fixed.** 
1.1) A new bug has been found where on PC & iOS UniSwap Wallet doesn't show, although it's in the list of recommended wallets.
2) Android Carousel persists only with the recommended wallets (it will only show the ones added into the list)
3) Android "Select Wallet" doesn't work anymore.

**Comment by 0xAsimetriq** [comment]
Closing in favour of #1012
